import type { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // 清空现有数据
  await knex('recipes').del();

  // 插入菜谱数据
  const recipes = [
    {
      id: 'recipe_001',
      name: '红烧鸡翅',
      name_en: 'Braised Chicken Wings',
      type: 'dinner',
      category: JSON.stringify(['肉类', '家常']),
      prep_time: 25,
      cook_time: 15,
      total_time: 40,
      difficulty: '简单',
      servings: '2人份',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '鸡翅中', amount: '8个', note: '约300g' },
          { name: '生姜', amount: '3片', note: '' },
          { name: '酱油', amount: '1勺', note: '约15ml' },
          { name: '料酒', amount: '1勺', note: '约15ml' },
          { name: '白糖', amount: '1小勺', note: '约5g' },
          { name: '食用油', amount: '适量', note: '' },
        ],
        steps: [
          { step: 1, action: '鸡翅洗净，在表面划两刀方便入味', time: 3, tools: ['刀', '砧板'], note: '' },
          { step: 2, action: '冷水下锅焯水，煮沸后捞出洗净浮沫', time: 5, tools: ['锅'], note: '去除血沫和腥味' },
          { step: 3, action: '锅中放少量油，放入鸡翅小火煎至两面金黄', time: 5, tools: ['平底锅'], note: '' },
          { step: 4, action: '加入姜片、酱油、料酒、白糖和适量水', time: 2, tools: [], note: '' },
          { step: 5, action: '大火煮沸后转小火焖煮15分钟', time: 15, tools: [], note: '期间翻面一次' },
          { step: 6, action: '大火收汁即可出锅', time: 3, tools: [], note: '收汁时要勤翻动' },
        ],
        seasonings: [
          { name: '酱油', amount: '1勺' },
          { name: '料酒', amount: '1勺' },
          { name: '白糖', amount: '1小勺' },
        ],
      }),
      baby_version: JSON.stringify({
        age_range: '1.5-2岁',
        ingredients: [
          { name: '鸡翅肉', amount: '2个鸡翅的量', note: '取自大人版已焯水的鸡翅' },
          { name: '胡萝卜', amount: '30g', note: '切小块' },
          { name: '西兰花', amount: '2朵', note: '约20g' },
        ],
        steps: [
          { step: 1, action: '取出大人版已焯水的鸡翅2个，去骨取肉', time: 5, tools: ['刀', '砧板'], note: '去骨时注意检查有没有小骨头' },
          { step: 2, action: '胡萝卜切小丁，西兰花切小朵', time: 3, tools: ['刀', '砧板'], note: '' },
          { step: 3, action: '胡萝卜和西兰花蒸10分钟至软烂', time: 10, tools: ['蒸锅'], note: '' },
          { step: 4, action: '将鸡翅肉、胡萝卜、西兰花混合打成泥', time: 3, tools: ['料理机'], note: '根据宝宝月龄调整颗粒粗细' },
        ],
        nutrition_tips: '富含优质蛋白质，促进宝宝生长发育；胡萝卜提供维生素A，有助于视力发育',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify([
        '可以提前腌制鸡翅更入味',
        '鸡翅可以在超市买大包装更划算',
      ]),
      tags: JSON.stringify(['鸡翅', '家常菜', '宝宝辅食']),
      is_active: true,
    },
    {
      id: 'recipe_002',
      name: '番茄鸡蛋面',
      name_en: 'Tomato Egg Noodles',
      type: 'breakfast',
      category: JSON.stringify(['主食', '快手']),
      prep_time: 15,
      cook_time: 10,
      total_time: 25,
      difficulty: '简单',
      servings: '2人份',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '面条', amount: '200g', note: '约2人份' },
          { name: '鸡蛋', amount: '2个', note: '' },
          { name: '番茄', amount: '2个', note: '约300g' },
          { name: '大葱', amount: '1根', note: '切碎' },
          { name: '食用油', amount: '适量', note: '' },
          { name: '盐', amount: '适量', note: '' },
        ],
        steps: [
          { step: 1, action: '番茄洗净切块，鸡蛋打散备用', time: 3, tools: ['刀', '砧板', '碗'], note: '' },
          { step: 2, action: '锅中放油，炒熟鸡蛋盛出备用', time: 3, tools: ['平底锅'], note: '不要炒太老' },
          { step: 3, action: '锅中再放少许油，炒香葱花，放入番茄炒出汁', time: 5, tools: ['平底锅'], note: '可以加一点点盐帮助出汁' },
          { step: 4, action: '加入适量水煮沸，放入面条煮熟', time: 8, tools: ['锅'], note: '' },
          { step: 5, action: '加入炒蛋，调味后即可出锅', time: 2, tools: [], note: '' },
        ],
        seasonings: [
          { name: '盐', amount: '适量' },
        ],
      }),
      baby_version: JSON.stringify({
        age_range: '1.5-2岁',
        ingredients: [
          { name: '细面条', amount: '30g', note: '选择宝宝专用面条' },
          { name: '鸡蛋黄', amount: '1个', note: '' },
          { name: '番茄', amount: '1/4个', note: '约30g' },
        ],
        steps: [
          { step: 1, action: '番茄去皮去籽，切小丁', time: 2, tools: ['刀', '砧板'], note: '可以用开水烫一下更容易去皮' },
          { step: 2, action: '番茄加水煮成番茄汤', time: 5, tools: ['小锅'], note: '' },
          { step: 3, action: '放入面条煮至软烂', time: 5, tools: [], note: '宝宝面条煮的时间要长一些' },
          { step: 4, action: '加入熟鸡蛋黄，压碎混合即可', time: 2, tools: [], note: '1.5岁以上可以吃蛋白' },
        ],
        nutrition_tips: '番茄富含维生素C和番茄红素，鸡蛋提供优质蛋白质',
        allergy_alert: '对鸡蛋过敏的宝宝慎用',
      }),
      cooking_tips: JSON.stringify([
        '番茄可以先用开水烫一下去皮',
        '面条选择自己喜欢的种类都可以',
      ]),
      tags: JSON.stringify(['早餐', '快手', '面条']),
      is_active: true,
    },
    {
      id: 'recipe_003',
      name: '清蒸鲈鱼',
      name_en: 'Steamed Sea Bass',
      type: 'lunch',
      category: JSON.stringify(['鱼类', '清淡']),
      prep_time: 20,
      cook_time: 12,
      total_time: 32,
      difficulty: '简单',
      servings: '2人份',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '鲈鱼', amount: '1条', note: '约500g' },
          { name: '生姜', amount: '5片', note: '' },
          { name: '大葱', amount: '2根', note: '切段' },
          { name: '酱油', amount: '2勺', note: '约30ml' },
          { name: '食用油', amount: '适量', note: '' },
        ],
        steps: [
          { step: 1, action: '鲈鱼去鳞去内脏洗净，在鱼身两面划几刀', time: 5, tools: ['刀', '砧板'], note: '' },
          { step: 2, action: '鱼身抹少许盐，放上姜片腌制10分钟', time: 10, tools: ['盘'], note: '' },
          { step: 3, action: '水开后放入鱼，大火蒸8-10分钟', time: 10, tools: ['蒸锅'], note: '根据鱼的大小调整时间' },
          { step: 4, action: '倒掉蒸出的水，放上葱丝', time: 2, tools: [], note: '' },
          { step: 5, action: '烧热油浇在葱丝上，淋上酱油即可', time: 2, tools: ['小锅'], note: '' },
        ],
        seasonings: [
          { name: '酱油', amount: '2勺' },
        ],
      }),
      baby_version: JSON.stringify({
        age_range: '1.5-2岁',
        ingredients: [
          { name: '鲈鱼肉', amount: '50g', note: '取自大人版已蒸熟的鱼' },
          { name: '胡萝卜', amount: '20g', note: '切小块' },
        ],
        steps: [
          { step: 1, action: '从蒸熟的鲈鱼上取肉，仔细检查有没有鱼刺', time: 5, tools: [], note: '一定要仔细去刺' },
          { step: 2, action: '胡萝卜蒸熟压成泥', time: 8, tools: ['蒸锅'], note: '' },
          { step: 3, action: '将鱼肉和胡萝卜泥混合即可', time: 2, tools: [], note: '可以适当加一点米汤调节稀稠' },
        ],
        nutrition_tips: '鲈鱼肉质细嫩，富含DHA，有助于宝宝大脑发育',
        allergy_alert: '对鱼类过敏的宝宝慎用',
      }),
      cooking_tips: JSON.stringify([
        '选择新鲜的鲈鱼，眼睛要清澈',
        '蒸鱼时间不宜过长，以免肉质变老',
      ]),
      tags: JSON.stringify(['鱼', '清淡', '蒸菜']),
      is_active: true,
    },
    {
      id: 'recipe_004',
      name: '南瓜焖饭',
      name_en: 'Pumpkin Rice',
      type: 'dinner',
      category: JSON.stringify(['主食', '素食']),
      prep_time: 15,
      cook_time: 35,
      total_time: 50,
      difficulty: '简单',
      servings: '2人份',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '大米', amount: '200g', note: '约1杯' },
          { name: '南瓜', amount: '300g', note: '切小块' },
          { name: '洋葱', amount: '1/4个', note: '切碎' },
          { name: '食用油', amount: '适量', note: '' },
          { name: '盐', amount: '适量', note: '' },
        ],
        steps: [
          { step: 1, action: '大米淘洗干净备用', time: 2, tools: ['碗'], note: '' },
          { step: 2, action: '南瓜去皮去籽切小块', time: 5, tools: ['刀', '砧板'], note: '' },
          { step: 3, action: '锅中放少许油，炒香洋葱碎', time: 3, tools: ['电饭锅'], note: '' },
          { step: 4, action: '放入大米、南瓜和水，按下煮饭键', time: 35, tools: ['电饭锅'], note: '水量和平时煮饭一样' },
          { step: 5, action: '煮好后撒上葱花即可', time: 2, tools: [], note: '' },
        ],
        seasonings: [
          { name: '盐', amount: '适量' },
        ],
      }),
      baby_version: JSON.stringify({
        age_range: '1.5-2岁',
        ingredients: [
          { name: '大米', amount: '50g', note: '' },
          { name: '南瓜', amount: '100g', note: '切小块' },
          { name: '鸡肉', amount: '30g', note: '切小块' },
        ],
        steps: [
          { step: 1, action: '大米淘洗干净，南瓜切小块', time: 5, tools: ['碗'], note: '' },
          { step: 2, action: '鸡肉焯水去腥', time: 5, tools: ['小锅'], note: '' },
          { step: 3, action: '将大米、南瓜、鸡肉放入电饭锅加水煮熟', time: 35, tools: ['电饭锅'], note: '可以多加一点水煮烂一些' },
          { step: 4, action: '将煮好的南瓜鸡肉粥搅拌均匀即可', time: 2, tools: [], note: '根据宝宝情况调整颗粒粗细' },
        ],
        nutrition_tips: '南瓜富含胡萝卜素和膳食纤维，有助于消化',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify([
        '南瓜选择金黄色的更甜',
        '电饭锅一锅出，方便快捷',
      ]),
      tags: JSON.stringify(['南瓜', '米饭', '一锅出']),
      is_active: true,
    },
    {
      id: 'recipe_005',
      name: '三文鱼炒饭',
      name_en: 'Salmon Fried Rice',
      type: 'lunch',
      category: JSON.stringify(['主食', '海鲜']),
      prep_time: 15,
      cook_time: 10,
      total_time: 25,
      difficulty: '简单',
      servings: '2人份',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '米饭', amount: '2碗', note: '隔夜饭更好' },
          { name: '三文鱼', amount: '150g', note: '切小块' },
          { name: '鸡蛋', amount: '2个', note: '' },
          { name: '洋葱', amount: '1/4个', note: '切碎' },
          { name: '胡萝卜', amount: '30g', note: '切小丁' },
          { name: '食用油', amount: '适量', note: '' },
          { name: '盐', amount: '适量', note: '' },
        ],
        steps: [
          { step: 1, action: '三文鱼切小块，用少许盐腌制', time: 5, tools: ['碗'], note: '' },
          { step: 2, action: '鸡蛋打散炒熟备用', time: 2, tools: ['平底锅'], note: '' },
          { step: 3, action: '锅中放油，炒香洋葱和胡萝卜丁', time: 3, tools: ['平底锅'], note: '' },
          { step: 4, action: '放入三文鱼炒变色', time: 3, tools: [], note: '' },
          { step: 5, action: '加入米饭翻炒，加入炒蛋，调味后出锅', time: 5, tools: [], note: '米饭要炒散' },
        ],
        seasonings: [
          { name: '盐', amount: '适量' },
        ],
      }),
      baby_version: JSON.stringify({
        age_range: '1.5-2岁',
        ingredients: [
          { name: '软米饭', amount: '50g', note: '' },
          { name: '三文鱼肉', amount: '40g', note: '去刺' },
          { name: '胡萝卜', amount: '20g', note: '切小丁' },
        ],
        steps: [
          { step: 1, action: '三文鱼蒸熟或煮熟，去刺压碎', time: 8, tools: ['小锅'], note: '一定要检查鱼刺' },
          { step: 2, action: '胡萝卜切小丁煮软', time: 5, tools: ['小锅'], note: '' },
          { step: 3, action: '将米饭、三文鱼、胡萝卜混合拌匀即可', time: 2, tools: [], note: '可以根据口味加一点宝宝酱油' },
        ],
        nutrition_tips: '三文鱼富含DHA和EPA，对大脑发育有益',
        allergy_alert: '对鱼类过敏的宝宝慎用',
      }),
      cooking_tips: JSON.stringify([
        '三文鱼不要炒太久，以免变老',
        '隔夜饭做炒饭颗粒分明',
      ]),
      tags: JSON.stringify(['三文鱼', '炒饭', '海鲜']),
      is_active: true,
    },
    // ============ 新增菜谱 ============
    {
      id: 'recipe_006',
      name: '红烧肉',
      name_en: 'Braised Pork Belly',
      type: 'dinner',
      category: JSON.stringify(['肉类', '家常', '猪肉']),
      prep_time: 20,
      cook_time: 60,
      total_time: 80,
      difficulty: '中等',
      servings: '3人份',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '五花肉', amount: '500g', note: '切3cm方块' },
          { name: '生姜', amount: '5片', note: '' },
          { name: '八角', amount: '2个', note: '' },
          { name: '桂皮', amount: '1小块', note: '' },
          { name: '酱油', amount: '3勺', note: '约45ml' },
          { name: '老抽', amount: '1勺', note: '上色用' },
          { name: '白糖', amount: '2勺', note: '约20g' },
          { name: '料酒', amount: '2勺', note: '约30ml' },
        ],
        steps: [
          { step: 1, action: '五花肉切块，冷水下锅焯水', time: 10, tools: ['锅'], note: '去血沫' },
          { step: 2, action: '捞出洗净，控干水分', time: 3, tools: [], note: '' },
          { step: 3, action: '锅中放少许油，放入白糖小火炒糖色', time: 5, tools: ['锅'], note: '糖色变深即可，不要炒糊' },
          { step: 4, action: '放入五花肉翻炒上色', time: 3, tools: [], note: '' },
          { step: 5, action: '加入酱油、老抽、料酒、姜片、八角、桂皮', time: 2, tools: [], note: '' },
          { step: 6, action: '加入开水没过肉，大火烧开转小火慢炖', time: 50, tools: [], note: '炖至软烂' },
          { step: 7, action: '大火收汁即可', time: 5, tools: [], note: '' },
        ],
        seasonings: [
          { name: '酱油', amount: '3勺' },
          { name: '老抽', amount: '1勺' },
          { name: '白糖', amount: '2勺' },
          { name: '料酒', amount: '2勺' },
        ],
      }),
      baby_version: JSON.stringify({
        age_range: '1.5-2岁',
        ingredients: [
          { name: '五花肉', amount: '30g', note: '取瘦肉部分' },
          { name: '土豆', amount: '30g', note: '切小块' },
          { name: '胡萝卜', amount: '20g', note: '切小块' },
        ],
        steps: [
          { step: 1, action: '五花肉去皮，取瘦肉部分切小块', time: 5, tools: ['刀', '砧板'], note: '' },
          { step: 2, action: '土豆、胡萝卜切小块', time: 3, tools: [], note: '' },
          { step: 3, action: '所有食材放入小锅，加水煮烂', time: 30, tools: ['小锅'], note: '煮至软烂' },
          { step: 4, action: '捞出食材，用勺子压成泥状', time: 3, tools: [], note: '' },
        ],
        nutrition_tips: '猪肉提供优质蛋白质和铁元素，有助于预防缺铁性贫血',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify([
        '炒糖色时要小火，糖色变焦会发苦',
        '炖肉时加开水，不要加冷水',
      ]),
      tags: JSON.stringify(['红烧肉', '猪肉', '家常菜']),
      is_active: true,
    },
    {
      id: 'recipe_007',
      name: '糖醋排骨',
      name_en: 'Sweet and Sour Ribs',
      type: 'dinner',
      category: JSON.stringify(['肉类', '猪肉', '酸甜']),
      prep_time: 15,
      cook_time: 30,
      total_time: 45,
      difficulty: '中等',
      servings: '2人份',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '排骨', amount: '400g', note: '切小段' },
          { name: '醋', amount: '3勺', note: '约45ml' },
          { name: '白糖', amount: '2勺', note: '约20g' },
          { name: '酱油', amount: '2勺', note: '约30ml' },
          { name: '料酒', amount: '1勺', note: '' },
          { name: '生姜', amount: '3片', note: '' },
        ],
        steps: [
          { step: 1, action: '排骨冷水下锅，加料酒姜片焯水', time: 10, tools: ['锅'], note: '' },
          { step: 2, action: '捞出洗净备用', time: 2, tools: [], note: '' },
          { step: 3, action: '锅中放油，放入排骨煎至两面金黄', time: 8, tools: ['平底锅'], note: '' },
          { step: 4, action: '加入醋、糖、酱油和适量水', time: 2, tools: [], note: '' },
          { step: 5, action: '大火烧开转中小火炖20分钟', time: 20, tools: [], note: '' },
          { step: 6, action: '大火收汁至浓稠', time: 5, tools: [], note: '' },
        ],
        seasonings: [
          { name: '醋', amount: '3勺' },
          { name: '白糖', amount: '2勺' },
          { name: '酱油', amount: '2勺' },
        ],
      }),
      baby_version: JSON.stringify({
        age_range: '1.5-2岁',
        ingredients: [
          { name: '排骨肉', amount: '30g', note: '去骨取肉' },
          { name: '苹果', amount: '20g', note: '去皮切小块' },
        ],
        steps: [
          { step: 1, action: '排骨煮熟，去骨取肉', time: 15, tools: ['锅'], note: '' },
          { step: 2, action: '苹果去皮切小块蒸熟', time: 10, tools: ['蒸锅'], note: '' },
          { step: 3, action: '将排骨肉和苹果混合压成泥', time: 3, tools: [], note: '' },
        ],
        nutrition_tips: '排骨富含钙质，苹果提供维生素和膳食纤维',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify([
        '糖醋比例可以根据个人口味调整',
        '收汁时要不断翻动防止糊锅',
      ]),
      tags: JSON.stringify(['排骨', '酸甜', '猪肉']),
      is_active: true,
    },
    {
      id: 'recipe_008',
      name: '蒜蓉西兰花',
      name_en: 'Garlic Broccoli',
      type: 'lunch',
      category: JSON.stringify(['蔬菜', '清淡', '快手']),
      prep_time: 10,
      cook_time: 5,
      total_time: 15,
      difficulty: '简单',
      servings: '2人份',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '西兰花', amount: '300g', note: '切成小朵' },
          { name: '大蒜', amount: '4瓣', note: '切末' },
          { name: '盐', amount: '适量', note: '' },
          { name: '食用油', amount: '适量', note: '' },
        ],
        steps: [
          { step: 1, action: '西兰花切成小朵，用盐水浸泡10分钟', time: 10, tools: ['碗'], note: '去除杂质' },
          { step: 2, action: '锅中烧水，加少许盐和油，放入西兰花焯水', time: 3, tools: ['锅'], note: '保持绿色' },
          { step: 3, action: '捞出沥干水分', time: 2, tools: [], note: '' },
          { step: 4, action: '锅中放油，爆香蒜末', time: 1, tools: ['锅'], note: '' },
          { step: 5, action: '放入西兰花翻炒，加盐调味即可', time: 2, tools: [], note: '' },
        ],
        seasonings: [
          { name: '盐', amount: '适量' },
        ],
      }),
      baby_version: JSON.stringify({
        age_range: '1-1.5岁',
        ingredients: [
          { name: '西兰花', amount: '30g', note: '取嫩部分' },
        ],
        steps: [
          { step: 1, action: '西兰花切成小朵，用盐水浸泡', time: 5, tools: [], note: '' },
          { step: 2, action: '蒸10分钟至软烂', time: 10, tools: ['蒸锅'], note: '' },
          { step: 3, action: '取出用勺子压成小块', time: 2, tools: [], note: '' },
        ],
        nutrition_tips: '西兰花富含维生素C和钙质，有助于增强免疫力',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify([
        '焯水时加少许盐和油能保持西兰花翠绿',
        '不要焯太久，保持脆爽口感',
      ]),
      tags: JSON.stringify(['西兰花', '蔬菜', '清淡']),
      is_active: true,
    },
    {
      id: 'recipe_009',
      name: '土豆炖牛肉',
      name_en: 'Beef Stew with Potatoes',
      type: 'dinner',
      category: JSON.stringify(['肉类', '牛肉', '炖菜']),
      prep_time: 20,
      cook_time: 90,
      total_time: 110,
      difficulty: '中等',
      servings: '3人份',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '牛腩', amount: '500g', note: '切块' },
          { name: '土豆', amount: '300g', note: '切块' },
          { name: '胡萝卜', amount: '1根', note: '切块' },
          { name: '洋葱', amount: '1个', note: '切块' },
          { name: '番茄酱', amount: '2勺', note: '' },
          { name: '酱油', amount: '2勺', note: '' },
          { name: '料酒', amount: '2勺', note: '' },
          { name: '生姜', amount: '5片', note: '' },
        ],
        steps: [
          { step: 1, action: '牛肉切块，冷水下锅加料酒焯水', time: 15, tools: ['锅'], note: '去血沫' },
          { step: 2, action: '捞出洗净，土豆胡萝卜切块', time: 5, tools: [], note: '' },
          { step: 3, action: '锅中放油，炒香洋葱和姜片', time: 5, tools: ['锅'], note: '' },
          { step: 4, action: '放入牛肉翻炒，加酱油和番茄酱', time: 5, tools: [], note: '' },
          { step: 5, action: '加入开水没过牛肉，大火烧开转小火', time: 60, tools: [], note: '炖1小时' },
          { step: 6, action: '加入土豆胡萝卜再炖30分钟', time: 30, tools: [], note: '' },
          { step: 7, action: '大火收汁，加盐调味', time: 5, tools: [], note: '' },
        ],
        seasonings: [
          { name: '酱油', amount: '2勺' },
          { name: '番茄酱', amount: '2勺' },
          { name: '盐', amount: '适量' },
        ],
      }),
      baby_version: JSON.stringify({
        age_range: '1.5-2岁',
        ingredients: [
          { name: '牛肉', amount: '30g', note: '取嫩部位' },
          { name: '土豆', amount: '30g', note: '' },
          { name: '胡萝卜', amount: '15g', note: '' },
        ],
        steps: [
          { step: 1, action: '牛肉切小块，反复焯水去血沫', time: 10, tools: ['小锅'], note: '' },
          { step: 2, action: '土豆、胡萝卜切小块', time: 3, tools: [], note: '' },
          { step: 3, action: '所有食材加少量水煮烂', time: 40, tools: ['小锅'], note: '' },
          { step: 4, action: '捞出压成泥状', time: 2, tools: [], note: '' },
        ],
        nutrition_tips: '牛肉富含铁和蛋白质，土豆提供碳水化合物',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify([
        '选择肥瘦相间的牛腩，炖出来更香',
        '炖牛肉要一次性加足水，中途不要加水',
      ]),
      tags: JSON.stringify(['牛肉', '土豆', '炖菜']),
      is_active: true,
    },
    {
      id: 'recipe_010',
      name: '虾仁蒸蛋',
      name_en: 'Steamed Egg with Shrimp',
      type: 'breakfast',
      category: JSON.stringify(['海鲜', '蒸菜', '快手']),
      prep_time: 10,
      cook_time: 15,
      total_time: 25,
      difficulty: '简单',
      servings: '2人份',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '鸡蛋', amount: '3个', note: '' },
          { name: '虾仁', amount: '100g', note: '' },
          { name: '温水', amount: '200ml', note: '鸡蛋液的1.5倍' },
          { name: '盐', amount: '适量', note: '' },
          { name: '酱油', amount: '1勺', note: '' },
          { name: '葱花', amount: '适量', note: '' },
        ],
        steps: [
          { step: 1, action: '虾仁去虾线，洗净备用', time: 3, tools: [], note: '' },
          { step: 2, action: '鸡蛋打散，加入温水和盐搅拌均匀', time: 3, tools: ['碗'], note: '过滤一下更细腻' },
          { step: 3, action: '将蛋液倒入盘中，放入虾仁', time: 2, tools: [], note: '' },
          { step: 4, action: '盖上保鲜膜，戳几个孔', time: 1, tools: [], note: '' },
          { step: 5, action: '水开后放入蒸8-10分钟', time: 10, tools: ['蒸锅'], note: '' },
          { step: 6, action: '出锅淋上酱油和葱花', time: 1, tools: [], note: '' },
        ],
        seasonings: [
          { name: '盐', amount: '适量' },
          { name: '酱油', amount: '1勺' },
        ],
      }),
      baby_version: JSON.stringify({
        age_range: '1-1.5岁',
        ingredients: [
          { name: '鸡蛋', amount: '1个', note: '' },
          { name: '虾仁', amount: '20g', note: '去虾线' },
        ],
        steps: [
          { step: 1, action: '虾仁去虾线，切成小块', time: 3, tools: [], note: '' },
          { step: 2, action: '鸡蛋打散，加入温水（蛋液的1.5倍）', time: 2, tools: ['碗'], note: '' },
          { step: 3, action: '将虾仁放入蛋液中，搅拌均匀', time: 1, tools: [], note: '' },
          { step: 4, action: '盖保鲜膜蒸8分钟', time: 8, tools: ['蒸锅'], note: '' },
          { step: 5, action: '取出放凉即可', time: 1, tools: [], note: '' },
        ],
        nutrition_tips: '虾仁富含优质蛋白质和钙，鸡蛋提供DHA',
        allergy_alert: '对鸡蛋或虾过敏的宝宝慎用',
      }),
      cooking_tips: JSON.stringify([
        '加温水可以让蒸蛋更嫩滑',
        '过滤蛋液可以去除气泡，蒸出来更平整',
      ]),
      tags: JSON.stringify(['虾', '蒸蛋', '海鲜']),
      is_active: true,
    },
    {
      id: 'recipe_011',
      name: '番茄牛腩面',
      name_en: 'Beef Noodles with Tomato',
      type: 'lunch',
      category: JSON.stringify(['主食', '牛肉', '酸甜']),
      prep_time: 15,
      cook_time: 40,
      total_time: 55,
      difficulty: '中等',
      servings: '2人份',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '牛腩', amount: '200g', note: '切块' },
          { name: '番茄', amount: '2个', note: '' },
          { name: '面条', amount: '200g', note: '' },
          { name: '洋葱', amount: '1/4个', note: '' },
          { name: '番茄酱', amount: '2勺', note: '' },
          { name: '酱油', amount: '1勺', note: '' },
          { name: '盐', amount: '适量', note: '' },
        ],
        steps: [
          { step: 1, action: '牛腩切块焯水，番茄切块', time: 5, tools: [], note: '' },
          { step: 2, action: '番茄去皮切块（开水烫一下好去皮）', time: 3, tools: [], note: '' },
          { step: 3, action: '锅中炒香洋葱，放入牛肉翻炒', time: 5, tools: [], note: '' },
          { step: 4, action: '加入番茄和番茄酱，加水炖30分钟', time: 30, tools: [], note: '' },
          { step: 5, action: '另起锅煮面条', time: 8, tools: ['锅'], note: '' },
          { step: 6, action: '面条盛入碗中，浇上番茄牛腩', time: 2, tools: [], note: '' },
        ],
        seasonings: [
          { name: '番茄酱', amount: '2勺' },
          { name: '酱油', amount: '1勺' },
          { name: '盐', amount: '适量' },
        ],
      }),
      baby_version: JSON.stringify({
        age_range: '1.5-2岁',
        ingredients: [
          { name: '牛肉', amount: '20g', note: '煮熟切碎' },
          { name: '番茄', amount: '30g', note: '去皮切碎' },
          { name: '宝宝面条', amount: '30g', note: '' },
        ],
        steps: [
          { step: 1, action: '牛肉煮熟切碎', time: 15, tools: ['小锅'], note: '' },
          { step: 2, action: '番茄去皮切碎', time: 3, tools: [], note: '' },
          { step: 3, action: '番茄加水煮成酱', time: 8, tools: [], note: '' },
          { step: 4, action: '放入面条煮软', time: 8, tools: [], note: '' },
          { step: 5, action: '加入牛肉碎拌匀', time: 2, tools: [], note: '' },
        ],
        nutrition_tips: '番茄富含维C，牛肉补铁，是营养丰富的组合',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify([
        '番茄选熟透的，酸甜味更浓',
        '炖牛肉时可以加一点山楂，更容易烂',
      ]),
      tags: JSON.stringify(['牛肉', '番茄', '面条']),
      is_active: true,
    },
    {
      id: 'recipe_012',
      name: '香煎鳕鱼',
      name_en: 'Pan-Fried Cod',
      type: 'dinner',
      category: JSON.stringify(['鱼类', '清淡', '海鲜']),
      prep_time: 10,
      cook_time: 15,
      total_time: 25,
      difficulty: '简单',
      servings: '2人份',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '鳕鱼', amount: '300g', note: '切块' },
          { name: '柠檬', amount: '半个', note: '' },
          { name: '盐', amount: '适量', note: '' },
          { name: '黑胡椒', amount: '适量', note: '' },
          { name: '黄油', amount: '20g', note: '' },
          { name: '蒜', amount: '2瓣', note: '' },
        ],
        steps: [
          { step: 1, action: '鳕鱼用厨房纸吸干水分', time: 2, tools: [], note: '' },
          { step: 2, action: '两面撒盐和黑胡椒腌制5分钟', time: 5, tools: [], note: '' },
          { step: 3, action: '锅中放黄油融化', time: 2, tools: ['平底锅'], note: '' },
          { step: 4, action: '放入鳕鱼，中火煎3分钟', time: 3, tools: [], note: '' },
          { step: 5, action: '翻面再煎3分钟', time: 3, tools: [], note: '' },
          { step: 6, action: '出锅挤上柠檬汁', time: 1, tools: [], note: '' },
        ],
        seasonings: [
          { name: '盐', amount: '适量' },
          { name: '黑胡椒', amount: '适量' },
        ],
      }),
      baby_version: JSON.stringify({
        age_range: '1-1.5岁',
        ingredients: [
          { name: '鳕鱼肉', amount: '40g', note: '无骨无刺' },
          { name: '胡萝卜', amount: '15g', note: '切小块' },
        ],
        steps: [
          { step: 1, action: '鳕鱼肉检查无刺，切小块', time: 3, tools: [], note: '仔细检查' },
          { step: 2, action: '胡萝卜切小块蒸熟', time: 10, tools: ['蒸锅'], note: '' },
          { step: 3, action: '将鳕鱼蒸5分钟', time: 5, tools: [], note: '' },
          { step: 4, action: '取出混合压成小块', time: 2, tools: [], note: '' },
        ],
        nutrition_tips: '鳕鱼肉质细嫩，富含优质蛋白和DHA',
        allergy_alert: '对鱼类过敏的宝宝慎用',
      }),
      cooking_tips: JSON.stringify([
        '鳕鱼不要煎太久，肉质会变老',
        '可以用柠檬去腥',
      ]),
      tags: JSON.stringify(['鱼', '海鲜', '煎']),
      is_active: true,
    },
    {
      id: 'recipe_013',
      name: '猪肉白菜水饺',
      name_en: 'Pork and Cabbage Dumplings',
      type: 'dinner',
      category: JSON.stringify(['主食', '面食', '猪肉']),
      prep_time: 40,
      cook_time: 10,
      total_time: 50,
      difficulty: '中等',
      servings: '3人份',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '面粉', amount: '300g', note: '' },
          { name: '猪肉馅', amount: '300g', note: '三分肥七分瘦' },
          { name: '白菜', amount: '300g', note: '' },
          { name: '葱', amount: '2根', note: '' },
          { name: '姜', amount: '3片', note: '' },
          { name: '酱油', amount: '2勺', note: '' },
          { name: '盐', amount: '适量', note: '' },
          { name: '香油', amount: '1勺', note: '' },
        ],
        steps: [
          { step: 1, action: '面粉加水揉成面团，醒20分钟', time: 20, tools: ['碗'], note: '' },
          { step: 2, action: '白菜切碎，撒盐杀水', time: 10, tools: [], note: '' },
          { step: 3, action: '猪肉馅加酱油、葱姜末、香油搅拌上劲', time: 5, tools: [], note: '' },
          { step: 4, action: '白菜挤干水分，放入肉馅中拌匀', time: 3, tools: [], note: '' },
          { step: 5, action: '面团搓条切剂子，擀成饺子皮', time: 10, tools: [], note: '' },
          { step: 6, action: '包饺子', time: 15, tools: [], note: '' },
          { step: 7, action: '水开下饺子，点3次水煮熟', time: 10, tools: ['锅'], note: '' },
        ],
        seasonings: [
          { name: '酱油', amount: '2勺' },
          { name: '香油', amount: '1勺' },
          { name: '盐', amount: '适量' },
        ],
      }),
      baby_version: JSON.stringify({
        age_range: '1.5-2岁',
        ingredients: [
          { name: '饺子皮', amount: '5张', note: '买的成品' },
          { name: '猪肉馅', amount: '30g', note: '' },
          { name: '白菜', amount: '20g', note: '' },
        ],
        steps: [
          { step: 1, action: '白菜切碎焯水', time: 5, tools: ['锅'], note: '' },
          { step: 2, action: '猪肉馅和白菜拌匀', time: 3, tools: [], note: '' },
          { step: 3, action: '取少量馅包小饺子', time: 10, tools: [], note: '' },
          { step: 4, action: '煮熟后切成小块', time: 8, tools: [], note: '' },
        ],
        nutrition_tips: '饺子营养全面，猪肉补铁，白菜富含维C',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify([
        '白菜一定要杀水，不然饺子馅会出水',
        '肉馅三分肥七分瘦更香',
      ]),
      tags: JSON.stringify(['饺子', '猪肉', '白菜']),
      is_active: true,
    },
    {
      id: 'recipe_014',
      name: '玉米排骨汤',
      name_en: 'Corn and Ribs Soup',
      type: 'lunch',
      category: JSON.stringify(['汤类', '猪肉', '炖汤']),
      prep_time: 15,
      cook_time: 90,
      total_time: 105,
      difficulty: '简单',
      servings: '3人份',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '排骨', amount: '400g', note: '' },
          { name: '玉米', amount: '1根', note: '切段' },
          { name: '胡萝卜', amount: '1根', note: '切块' },
          { name: '姜', amount: '3片', note: '' },
          { name: '料酒', amount: '1勺', note: '' },
          { name: '盐', amount: '适量', note: '' },
        ],
        steps: [
          { step: 1, action: '排骨冷水下锅，加料酒焯水', time: 15, tools: ['锅'], note: '' },
          { step: 2, action: '捞出洗净，玉米胡萝卜切块', time: 5, tools: [], note: '' },
          { step: 3, action: '砂锅中放入排骨、姜片，加足水', time: 3, tools: ['砂锅'], note: '' },
          { step: 4, action: '大火烧开撇去浮沫', time: 5, tools: [], note: '' },
          { step: 5, action: '放入玉米胡萝卜，小火炖1小时', time: 60, tools: [], note: '' },
          { step: 6, action: '加盐调味即可', time: 2, tools: [], note: '' },
        ],
        seasonings: [
          { name: '盐', amount: '适量' },
          { name: '料酒', amount: '1勺' },
        ],
      }),
      baby_version: JSON.stringify({
        age_range: '1-1.5岁',
        ingredients: [
          { name: '排骨', amount: '30g', note: '取瘦肉' },
          { name: '玉米', amount: '20g', note: '取颗粒' },
          { name: '胡萝卜', amount: '15g', note: '' },
        ],
        steps: [
          { step: 1, action: '排骨焯水去血沫', time: 10, tools: ['小锅'], note: '' },
          { step: 2, action: '玉米取颗粒，胡萝卜切小块', time: 5, tools: [], note: '' },
          { step: 3, action: '所有食材加水煮烂', time: 40, tools: [], note: '' },
          { step: 4, action: '捞出食材压成小块', time: 3, tools: [], note: '' },
        ],
        nutrition_tips: '排骨补钙，玉米富含膳食纤维',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify([
        '一次性加足水，中途不要加水',
        '小火慢炖汤更浓',
      ]),
      tags: JSON.stringify(['排骨', '汤', '玉米']),
      is_active: true,
    },
    {
      id: 'recipe_015',
      name: '葱油拌面',
      name_en: 'Scallion Oil Noodles',
      type: 'breakfast',
      category: JSON.stringify(['主食', '快手', '面条']),
      prep_time: 10,
      cook_time: 10,
      total_time: 20,
      difficulty: '简单',
      servings: '2人份',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '面条', amount: '200g', note: '细圆面' },
          { name: '小葱', amount: '100g', note: '' },
          { name: '食用油', amount: '50ml', note: '' },
          { name: '酱油', amount: '3勺', note: '' },
          { name: '白糖', amount: '1勺', note: '' },
        ],
        steps: [
          { step: 1, action: '小葱切葱花', time: 5, tools: ['刀'], note: '' },
          { step: 2, action: '锅中烧热油，浇在葱花上制成葱油', time: 3, tools: ['锅'], note: '小心烫' },
          { step: 3, action: '酱油和白糖调匀', time: 1, tools: [], note: '' },
          { step: 4, action: '煮面条', time: 5, tools: ['锅'], note: '' },
          { step: 5, action: '面条捞出沥干，浇上葱油和酱油拌匀', time: 2, tools: [], note: '' },
        ],
        seasonings: [
          { name: '酱油', amount: '3勺' },
          { name: '白糖', amount: '1勺' },
        ],
      }),
      baby_version: JSON.stringify({
        age_range: '1.5-2岁',
        ingredients: [
          { name: '宝宝面条', amount: '30g', note: '' },
          { name: '小葱', amount: '5g', note: '切碎' },
        ],
        steps: [
          { step: 1, action: '小葱切碎', time: 2, tools: [], note: '' },
          { step: 2, action: '少量油炒香葱花', time: 2, tools: ['小锅'], note: '' },
          { step: 3, action: '加入少许酱油和水煮开', time: 3, tools: [], note: '' },
          { step: 4, action: '煮面条，捞出拌入葱花酱油', time: 8, tools: [], note: '' },
        ],
        nutrition_tips: '简单易做，葱花提供维生素',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify([
        '油烧热再浇葱花，香味更浓',
        '可以根据口味加一点醋',
      ]),
      tags: JSON.stringify(['面条', '早餐', '快手']),
      is_active: true,
    },
    {
      id: 'recipe_016',
      name: '胡萝卜炒肉丝',
      name_en: 'Stir-Fried Pork with Carrots',
      type: 'lunch',
      category: JSON.stringify(['肉类', '猪肉', '快手']),
      prep_time: 15,
      cook_time: 10,
      total_time: 25,
      difficulty: '简单',
      servings: '2人份',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '猪里脊', amount: '200g', note: '切丝' },
          { name: '胡萝卜', amount: '1根', note: '切丝' },
          { name: '青椒', amount: '1个', note: '切丝' },
          { name: '蒜', amount: '2瓣', note: '' },
          { name: '酱油', amount: '1勺', note: '' },
          { name: '盐', amount: '适量', note: '' },
          { name: '淀粉', amount: '1勺', note: '' },
        ],
        steps: [
          { step: 1, action: '肉丝加淀粉和少许酱油腌制', time: 5, tools: ['碗'], note: '' },
          { step: 2, action: '胡萝卜、青椒切丝', time: 5, tools: [], note: '' },
          { step: 3, action: '锅中放油，先炒肉丝变色盛出', time: 3, tools: ['锅'], note: '' },
          { step: 4, action: '再炒胡萝卜丝和青椒丝', time: 3, tools: [], note: '' },
          { step: 5, action: '放入肉丝一起翻炒，加盐调味', time: 3, tools: [], note: '' },
        ],
        seasonings: [
          { name: '酱油', amount: '1勺' },
          { name: '盐', amount: '适量' },
          { name: '淀粉', amount: '1勺' },
        ],
      }),
      baby_version: JSON.stringify({
        age_range: '1-1.5岁',
        ingredients: [
          { name: '猪肉', amount: '20g', note: '剁碎' },
          { name: '胡萝卜', amount: '20g', note: '切小块' },
        ],
        steps: [
          { step: 1, action: '胡萝卜切小块蒸熟', time: 15, tools: ['蒸锅'], note: '' },
          { step: 2, action: '猪肉剁碎煮熟', time: 10, tools: ['小锅'], note: '' },
          { step: 3, action: '混合压成小块', time: 2, tools: [], note: '' },
        ],
        nutrition_tips: '胡萝卜富含胡萝卜素，对视力有益',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify([
        '肉丝提前腌制更嫩',
        '炒的时间不要太长，保持脆爽',
      ]),
      tags: JSON.stringify(['胡萝卜', '猪肉', '快手']),
      is_active: true,
    },
    {
      id: 'recipe_017',
      name: '紫菜蛋花汤',
      name_en: 'Seaweed Egg Drop Soup',
      type: 'breakfast',
      category: JSON.stringify(['汤类', '快手', '海鲜']),
      prep_time: 5,
      cook_time: 10,
      total_time: 15,
      difficulty: '简单',
      servings: '2人份',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '紫菜', amount: '10g', note: '' },
          { name: '鸡蛋', amount: '2个', note: '' },
          { name: '虾皮', amount: '1把', note: '' },
          { name: '盐', amount: '适量', note: '' },
          { name: '香油', amount: '少许', note: '' },
          { name: '葱花', amount: '适量', note: '' },
        ],
        steps: [
          { step: 1, action: '紫菜撕成小块，鸡蛋打散', time: 3, tools: ['碗'], note: '' },
          { step: 2, action: '锅中烧水，放入紫菜和虾皮', time: 5, tools: ['锅'], note: '' },
          { step: 3, action: '水开后转小火，慢慢倒入蛋液', time: 2, tools: [], note: '' },
          { step: 4, action: '蛋花形成后关火，加盐和香油', time: 1, tools: [], note: '' },
          { step: 5, action: '盛出撒上葱花', time: 1, tools: [], note: '' },
        ],
        seasonings: [
          { name: '盐', amount: '适量' },
          { name: '香油', amount: '少许' },
        ],
      }),
      baby_version: JSON.stringify({
        age_range: '1-1.5岁',
        ingredients: [
          { name: '紫菜', amount: '3g', note: '撕碎' },
          { name: '鸡蛋', amount: '1个', note: '' },
        ],
        steps: [
          { step: 1, action: '紫菜撕碎，鸡蛋打散', time: 2, tools: [], note: '' },
          { step: 2, action: '烧水后放入紫菜煮3分钟', time: 5, tools: ['小锅'], note: '' },
          { step: 3, action: '倒入蛋液形成蛋花', time: 2, tools: [], note: '' },
          { step: 4, action: '盛出放凉即可', time: 1, tools: [], note: '' },
        ],
        nutrition_tips: '紫菜富含碘和铁，鸡蛋提供优质蛋白',
        allergy_alert: '对鸡蛋过敏的宝宝慎用',
      }),
      cooking_tips: JSON.stringify([
        '倒蛋液时要边倒边搅，蛋花才漂亮',
        '关火后再调味，汤更清',
      ]),
      tags: JSON.stringify(['紫菜', '汤', '快手']),
      is_active: true,
    },
    {
      id: 'recipe_018',
      name: '苹果松饼',
      name_en: 'Apple Pancakes',
      type: 'breakfast',
      category: JSON.stringify(['主食', '甜点', '水果']),
      prep_time: 15,
      cook_time: 15,
      total_time: 30,
      difficulty: '简单',
      servings: '2人份',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '面粉', amount: '100g', note: '' },
          { name: '苹果', amount: '1个', note: '去皮擦丝' },
          { name: '鸡蛋', amount: '1个', note: '' },
          { name: '牛奶', amount: '80ml', note: '' },
          { name: '白糖', amount: '2勺', note: '' },
          { name: '泡打粉', amount: '3g', note: '' },
          { name: '黄油', amount: '20g', note: '' },
        ],
        steps: [
          { step: 1, action: '苹果去皮擦成细丝', time: 5, tools: ['擦丝器'], note: '' },
          { step: 2, action: '面粉、泡打粉、白糖混合', time: 3, tools: ['碗'], note: '' },
          { step: 3, action: '加入鸡蛋、牛奶搅拌成面糊', time: 3, tools: [], note: '' },
          { step: 4, action: '放入苹果丝拌匀', time: 2, tools: [], note: '' },
          { step: 5, action: '平底锅小火，舀入面糊煎至两面金黄', time: 15, tools: ['平底锅'], note: '' },
        ],
        seasonings: [],
      }),
      baby_version: JSON.stringify({
        age_range: '1-1.5岁',
        ingredients: [
          { name: '苹果', amount: '30g', note: '去皮擦丝' },
          { name: '面粉', amount: '20g', note: '' },
          { name: '鸡蛋', amount: '1个', note: '只用蛋黄' },
          { name: '牛奶', amount: '20ml', note: '' },
        ],
        steps: [
          { step: 1, action: '苹果去皮擦成细丝', time: 3, tools: [], note: '' },
          { step: 2, action: '面粉、蛋黄、牛奶调成面糊', time: 3, tools: ['碗'], note: '' },
          { step: 3, action: '放入苹果丝拌匀', time: 1, tools: [], note: '' },
          { step: 4, action: '小火煎成小饼', time: 8, tools: ['平底锅'], note: '' },
        ],
        nutrition_tips: '苹果富含果胶和维生素，松饼软糯易消化',
        allergy_alert: '对鸡蛋过敏的宝宝注意',
      }),
      cooking_tips: JSON.stringify([
        '苹果丝要细，煎的时候才容易熟',
        '全程小火，防止煎糊',
      ]),
      tags: JSON.stringify(['苹果', '早餐', '甜点']),
      is_active: true,
    },
    {
      id: 'recipe_019',
      name: '清炒菠菜',
      name_en: 'Stir-Fried Spinach',
      type: 'lunch',
      category: JSON.stringify(['蔬菜', '清淡', '快手']),
      prep_time: 5,
      cook_time: 3,
      total_time: 8,
      difficulty: '简单',
      servings: '2人份',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '菠菜', amount: '300g', note: '' },
          { name: '蒜', amount: '2瓣', note: '' },
          { name: '盐', amount: '适量', note: '' },
          { name: '食用油', amount: '适量', note: '' },
        ],
        steps: [
          { step: 1, action: '菠菜洗净，摘去根部', time: 3, tools: [], note: '' },
          { step: 2, action: '锅中烧水，加少许盐和油，放入菠菜焯水', time: 1, tools: ['锅'], note: '保持绿色' },
          { step: 3, action: '捞出沥干水分', time: 1, tools: [], note: '' },
          { step: 4, action: '锅中放油，爆香蒜末', time: 1, tools: ['锅'], note: '' },
          { step: 5, action: '放入菠菜翻炒，加盐调味', time: 2, tools: [], note: '' },
        ],
        seasonings: [
          { name: '盐', amount: '适量' },
        ],
      }),
      baby_version: JSON.stringify({
        age_range: '1-1.5岁',
        ingredients: [
          { name: '菠菜', amount: '30g', note: '取嫩叶' },
        ],
        steps: [
          { step: 1, action: '菠菜洗净，取嫩叶', time: 3, tools: [], note: '' },
          { step: 2, action: '烧水焯2分钟', time: 3, tools: ['小锅'], note: '' },
          { step: 3, action: '捞出切碎', time: 2, tools: [], note: '' },
        ],
        nutrition_tips: '菠菜富含铁和叶酸，有助于预防贫血',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify([
        '菠菜焯水可以去除草酸',
        '不要炒太久，保持脆爽',
      ]),
      tags: JSON.stringify(['菠菜', '蔬菜', '清淡']),
      is_active: true,
    },
    {
      id: 'recipe_020',
      name: '香蕉蒸糕',
      name_en: 'Steamed Banana Cake',
      type: 'breakfast',
      category: JSON.stringify(['主食', '甜点', '水果']),
      prep_time: 10,
      cook_time: 20,
      total_time: 30,
      difficulty: '简单',
      servings: '2人份',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '香蕉', amount: '2根', note: '熟透的' },
          { name: '面粉', amount: '100g', note: '' },
          { name: '鸡蛋', amount: '1个', note: '' },
          { name: '牛奶', amount: '50ml', note: '' },
          { name: '白糖', amount: '1勺', note: '' },
          { name: '酵母', amount: '3g', note: '' },
        ],
        steps: [
          { step: 1, action: '香蕉压成泥', time: 3, tools: ['碗'], note: '' },
          { step: 2, action: '加入鸡蛋、牛奶、白糖搅拌', time: 3, tools: [], note: '' },
          { step: 3, action: '加入面粉和酵母，搅拌成面糊', time: 3, tools: [], note: '' },
          { step: 4, action: '面糊倒入模具，醒发20分钟', time: 20, tools: [], note: '' },
          { step: 5, action: '冷水上锅蒸20分钟', time: 20, tools: ['蒸锅'], note: '' },
        ],
        seasonings: [],
      }),
      baby_version: JSON.stringify({
        age_range: '1-1.5岁',
        ingredients: [
          { name: '香蕉', amount: '30g', note: '熟透的' },
          { name: '面粉', amount: '20g', note: '' },
          { name: '鸡蛋', amount: '1个', note: '只用蛋黄' },
        ],
        steps: [
          { step: 1, action: '香蕉压成泥', time: 2, tools: [], note: '' },
          { step: 2, action: '加入蛋黄和面粉调成糊', time: 3, tools: ['碗'], note: '' },
          { step: 3, action: '倒入小蒸碗，蒸10分钟', time: 10, tools: ['蒸锅'], note: '' },
          { step: 4, action: '取出放凉即可', time: 1, tools: [], note: '' },
        ],
        nutrition_tips: '香蕉富含钾和膳食纤维，易于消化',
        allergy_alert: '对鸡蛋过敏的宝宝注意',
      }),
      cooking_tips: JSON.stringify([
        '选择熟透的香蕉，香味更浓',
        '蒸的时候要小火，防止塌陷',
      ]),
      tags: JSON.stringify(['香蕉', '蒸糕', '早餐']),
      is_active: true,
    },
  ];

  await knex('recipes').insert(recipes);
}
