import type { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  await knex('baby_stages').del();

  await knex('baby_stages').insert([
    {
      stage: '6-8m',
      name: '辅食初期',
      age_range: '6-8个月',
      age_min: 6,
      age_max: 8,
      can_eat: JSON.stringify(['大米粥/米粉', '南瓜泥', '胡萝卜泥', '红薯泥', '土豆泥', '苹果泥', '香蕉泥', '梨泥', '西葫芦泥', '菠菜泥']),
      cannot_eat: JSON.stringify(['蜂蜜', '整颗坚果', '牛奶（饮用）', '蛋白', '海鲜', '添加盐/糖/调料', '硬质食物']),
      texture_desc: '完全泥状，光滑无颗粒，从稀到稠循序渐进',
      meal_frequency: '每天1-2次辅食，母乳/配方奶为主（每日500-700ml）',
      key_nutrients: JSON.stringify(['铁', '锌', '维生素A', '维生素C']),
      guide_tips: JSON.stringify([
        '每次只引入一种新食材，观察3-5天无过敏再尝试下一种',
        '从1-2勺开始，逐步增加到2-3勺',
        '辅食时间选在宝宝不太饿也不太饱时（喂奶后1小时左右）',
        '首选强化铁米粉，这是6月龄最重要的营养补充',
      ]),
    },
    {
      stage: '8-10m',
      name: '辅食早期',
      age_range: '8-10个月',
      age_min: 8,
      age_max: 10,
      can_eat: JSON.stringify(['蛋黄', '鱼泥（去刺）', '豆腐', '稠粥/软面条', '肉泥（猪/鸡/牛）', '各类蔬菜泥', '多种水果泥', '豆类（煮烂压碎）']),
      cannot_eat: JSON.stringify(['蜂蜜', '整颗坚果', '牛奶（饮用）', '蛋白（慎用）', '海鲜（慎用）', '盐/糖/调料', '辛辣食物']),
      texture_desc: '细腻糊状，可有极小颗粒（约1-2mm），练习咀嚼意识',
      meal_frequency: '每天2次辅食，母乳/配方奶为主（每日500ml左右）',
      key_nutrients: JSON.stringify(['铁', '锌', '蛋白质', '维生素A', 'DHA']),
      guide_tips: JSON.stringify([
        '引入蛋黄：从1/4个开始，观察无过敏再逐步增加到整个蛋黄',
        '引入肉类：以瘦肉泥为主，优先猪肝（补铁）每周1-2次',
        '可以开始尝试手指食物（软烂的食物块，让宝宝自己抓）',
        '用餐时让宝宝坐在餐椅，培养良好用餐习惯',
      ]),
    },
    {
      stage: '10-12m',
      name: '辅食中期',
      age_range: '10-12个月',
      age_min: 10,
      age_max: 12,
      can_eat: JSON.stringify(['全蛋（蛋黄+蛋白）', '各类鱼虾（慎重引入）', '豆腐', '软饭/面条', '各类肉类', '各类蔬菜（细碎）', '各类水果', '少量奶酪']),
      cannot_eat: JSON.stringify(['蜂蜜', '整颗坚果', '牛奶（大量饮用）', '腌制食品', '高盐高糖食品', '油炸食品']),
      texture_desc: '细碎状，约3-5mm小粒，手指食物可增多，练习咀嚼',
      meal_frequency: '每天2-3次辅食，母乳/配方奶（每日400-500ml）',
      key_nutrients: JSON.stringify(['铁', '钙', '锌', '蛋白质', '维生素D']),
      guide_tips: JSON.stringify([
        '10月后可以尝试引入蛋白，从少量开始观察',
        '开始引入家庭软食，让宝宝参与家庭用餐',
        '鼓励自主进食，接受宝宝弄脏的过程',
        '食物多样化，每周尽量覆盖谷薯、蔬菜、水果、肉蛋、豆类',
      ]),
    },
    {
      stage: '12-18m',
      name: '辅食后期',
      age_range: '12-18个月',
      age_min: 12,
      age_max: 18,
      can_eat: JSON.stringify(['所有家常食材（合理烹饪）', '全蛋', '各类鱼虾', '牛奶/酸奶', '坚果酱（非整颗）', '豆制品', '各类蔬菜水果']),
      cannot_eat: JSON.stringify(['整颗坚果/葡萄/樱桃（噎呛风险）', '高盐高糖食品', '腌制/熏制食品', '含咖啡因饮料', '蜂蜜（仍建议避免）']),
      texture_desc: '接近成人软食，约1cm小块，培养独立咀嚼能力',
      meal_frequency: '每天3次正餐+1-2次加餐，母乳/配方奶可继续（每日300-400ml）',
      key_nutrients: JSON.stringify(['钙', '铁', '锌', '维生素D', 'Omega-3']),
      guide_tips: JSON.stringify([
        '12月后可引入少量酱油等调料，但整体保持清淡',
        '牛奶可作为主要饮品引入（每日300-500ml）',
        '鼓励和家人同桌吃饭，模仿大人用餐',
        '食物的多样性比数量更重要，每天尽量12种以上食材',
      ]),
    },
    {
      stage: '18-24m',
      name: '幼儿早期',
      age_range: '18-24个月',
      age_min: 18,
      age_max: 24,
      can_eat: JSON.stringify(['几乎所有家常食材', '各类坚果（磨碎或酱）', '各类海鲜', '发酵食品（少量）', '豆制品']),
      cannot_eat: JSON.stringify(['整颗小粒坚果/葡萄（仍有噎呛风险）', '过度加工食品', '含糖饮料', '油炸食品（少量）']),
      texture_desc: '接近成人正常食物，培养独立使用餐具',
      meal_frequency: '每天3次正餐+2次加餐，奶类300-400ml/天',
      key_nutrients: JSON.stringify(['钙', '铁', '锌', '维生素A', '维生素C', '膳食纤维']),
      guide_tips: JSON.stringify([
        '让宝宝参与简单的备餐过程（洗菜、撕菜叶），增加对食物的兴趣',
        '不强迫进食，尊重宝宝的饥饱信号',
        '加餐选择水果、奶制品、坚果酱，避免高糖零食',
        '开始培养用勺子独立进食，可以接受宝宝洒落食物',
      ]),
    },
    {
      stage: '24-36m',
      name: '幼儿期',
      age_range: '24-36个月',
      age_min: 24,
      age_max: 36,
      can_eat: JSON.stringify(['所有家常食材', '各类坚果（磨碎）', '各类食物', '发酵食品']),
      cannot_eat: JSON.stringify(['整颗小粒坚果（仍建议避免）', '含糖饮料/碳酸饮料', '过度腌制/熏制食品', '过多油炸食品']),
      texture_desc: '完全接近成人食物，可以吃小粒水果但仍需注意形状',
      meal_frequency: '每天3次正餐+1-2次加餐，奶类300-400ml/天',
      key_nutrients: JSON.stringify(['钙', '铁', '锌', '维生素D', '膳食纤维', '蛋白质']),
      guide_tips: JSON.stringify([
        '2岁后可以开始吃和大人完全相同的食物，只需控制盐糖用量',
        '培养自主进食，用餐时间固定，避免边吃边玩',
        '鼓励尝试各种颜色的蔬菜，用游戏方式引导不挑食',
        '每天保证至少30分钟户外活动，配合均衡饮食促进生长',
      ]),
    },
  ]);
}
