import type { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  await knex('recipes').insert([
    // ===== 6-8m 辅食初期（泥状）=====
    {
      id: 'baby_001',
      name: '南瓜米糊',
      name_en: 'Pumpkin Rice Cereal',
      type: 'baby',
      category: JSON.stringify(['辅食', '泥糊']),
      prep_time: 5,
      cook_time: 15,
      total_time: 20,
      difficulty: '简单',
      servings: '1份',
      stage: '6-8m',
      first_intro: false,
      key_nutrients: JSON.stringify(['维生素A', '铁', '锌']),
      scene_tags: JSON.stringify(['日常', '入门']),
      texture_level: 'puree',
      adult_version: JSON.stringify({
        ingredients: [{ name: '南瓜', amount: '200g', note: '去皮切块' }],
        steps: [
          { step: 1, action: '南瓜去皮切块，蒸15分钟至软烂', time: 15, tools: ['蒸锅'], note: '' },
          { step: 2, action: '南瓜压泥，可炒菜或做汤', time: 3, tools: [], note: '' },
        ],
        seasonings: [],
      }),
      baby_version: JSON.stringify({
        age_range: '6-8个月',
        ingredients: [
          { name: '南瓜', amount: '50g', note: '去皮去籽' },
          { name: '婴儿米粉', amount: '1勺', note: '强化铁' },
          { name: '母乳/配方奶', amount: '适量', note: '调稀稠度' },
        ],
        steps: [
          { step: 1, action: '南瓜蒸熟压成细腻泥状', time: 15, tools: ['蒸锅'], note: '确保无颗粒' },
          { step: 2, action: '米粉用温水冲调，加入南瓜泥混合均匀', time: 3, tools: [], note: '先从稀糊开始' },
        ],
        nutrition_tips: '南瓜富含β-胡萝卜素，补充维生素A；搭配强化铁米粉满足铁需求',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify(['南瓜蒸熟后用纱布滤掉颗粒更细腻', '可批量蒸南瓜冷冻备用']),
      tags: JSON.stringify(['辅食', '南瓜', '6个月', '泥糊']),
      is_active: true,
    },
    {
      id: 'baby_002',
      name: '胡萝卜泥',
      name_en: 'Carrot Puree',
      type: 'baby',
      category: JSON.stringify(['辅食', '泥糊']),
      prep_time: 5,
      cook_time: 15,
      total_time: 20,
      difficulty: '简单',
      servings: '1份',
      stage: '6-8m',
      first_intro: true,
      key_nutrients: JSON.stringify(['维生素A', '维生素C', 'β-胡萝卜素']),
      scene_tags: JSON.stringify(['日常', '首次引入']),
      texture_level: 'puree',
      adult_version: JSON.stringify({
        ingredients: [{ name: '胡萝卜', amount: '150g', note: '' }],
        steps: [
          { step: 1, action: '胡萝卜切丁，加油炒软或蒸熟', time: 10, tools: ['锅'], note: '' },
        ],
        seasonings: [{ name: '盐', amount: '少量' }],
      }),
      baby_version: JSON.stringify({
        age_range: '6-8个月',
        ingredients: [
          { name: '胡萝卜', amount: '50g', note: '去皮' },
        ],
        steps: [
          { step: 1, action: '胡萝卜去皮切块，蒸15分钟', time: 15, tools: ['蒸锅'], note: '' },
          { step: 2, action: '用搅拌机打成细腻泥，过筛去除纤维', time: 3, tools: ['搅拌机'], note: '' },
        ],
        nutrition_tips: 'β-胡萝卜素在体内转化为维生素A，促进视力和免疫力发育',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify(['胡萝卜加少量油蒸可提高维生素A吸收率', '初次引入只喂1-2勺，观察3天']),
      tags: JSON.stringify(['辅食', '胡萝卜', '6个月', '首次引入']),
      is_active: true,
    },
    {
      id: 'baby_003',
      name: '苹果泥',
      name_en: 'Apple Puree',
      type: 'baby',
      category: JSON.stringify(['辅食', '水果']),
      prep_time: 5,
      cook_time: 0,
      total_time: 5,
      difficulty: '简单',
      servings: '1份',
      stage: '6-8m',
      first_intro: true,
      key_nutrients: JSON.stringify(['维生素C', '膳食纤维', '果糖']),
      scene_tags: JSON.stringify(['日常', '首次引入', '快手']),
      texture_level: 'puree',
      adult_version: JSON.stringify({
        ingredients: [{ name: '苹果', amount: '1个', note: '' }],
        steps: [{ step: 1, action: '苹果洗净切块直接食用', time: 2, tools: [], note: '' }],
        seasonings: [],
      }),
      baby_version: JSON.stringify({
        age_range: '6-8个月',
        ingredients: [{ name: '苹果', amount: '半个', note: '去皮去核' }],
        steps: [
          { step: 1, action: '苹果去皮去核，用研磨碗磨成泥', time: 5, tools: ['研磨碗'], note: '或蒸熟后打泥' },
        ],
        nutrition_tips: '维生素C丰富，有助于铁的吸收；膳食纤维促进消化',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify(['新鲜苹果泥氧化快，现做现吃', '便秘宝宝推荐，腹泻宝宝少吃']),
      tags: JSON.stringify(['辅食', '苹果', '6个月', '水果泥']),
      is_active: true,
    },
    {
      id: 'baby_004',
      name: '红薯泥',
      name_en: 'Sweet Potato Puree',
      type: 'baby',
      category: JSON.stringify(['辅食', '泥糊']),
      prep_time: 5,
      cook_time: 20,
      total_time: 25,
      difficulty: '简单',
      servings: '1份',
      stage: '6-8m',
      first_intro: true,
      key_nutrients: JSON.stringify(['维生素A', '钾', '膳食纤维']),
      scene_tags: JSON.stringify(['日常', '首次引入']),
      texture_level: 'puree',
      adult_version: JSON.stringify({
        ingredients: [{ name: '红薯', amount: '200g', note: '' }],
        steps: [{ step: 1, action: '红薯蒸熟或烤熟，直接食用', time: 20, tools: ['蒸锅'], note: '' }],
        seasonings: [],
      }),
      baby_version: JSON.stringify({
        age_range: '6-8个月',
        ingredients: [{ name: '红薯', amount: '50g', note: '去皮' }],
        steps: [
          { step: 1, action: '红薯去皮切块，蒸20分钟至软烂', time: 20, tools: ['蒸锅'], note: '' },
          { step: 2, action: '趁热压成细腻泥状，加少量母乳调稀', time: 3, tools: [], note: '' },
        ],
        nutrition_tips: '天然甜味宝宝爱吃，富含维生素A和钾，促进肠道蠕动',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify(['红薯甜度高，不需要额外加糖', '可以和米粉混合食用']),
      tags: JSON.stringify(['辅食', '红薯', '6个月', '泥糊']),
      is_active: true,
    },
    {
      id: 'baby_005',
      name: '菠菜泥米糊',
      name_en: 'Spinach Rice Puree',
      type: 'baby',
      category: JSON.stringify(['辅食', '蔬菜']),
      prep_time: 5,
      cook_time: 10,
      total_time: 15,
      difficulty: '简单',
      servings: '1份',
      stage: '6-8m',
      first_intro: false,
      key_nutrients: JSON.stringify(['铁', '叶酸', '维生素K']),
      scene_tags: JSON.stringify(['日常', '补铁']),
      texture_level: 'puree',
      adult_version: JSON.stringify({
        ingredients: [{ name: '菠菜', amount: '100g', note: '' }],
        steps: [
          { step: 1, action: '菠菜焯水1分钟，捞出切碎炒菜', time: 5, tools: ['锅'], note: '' },
        ],
        seasonings: [{ name: '盐', amount: '少量' }, { name: '蒜', amount: '2瓣' }],
      }),
      baby_version: JSON.stringify({
        age_range: '6-8个月',
        ingredients: [
          { name: '菠菜叶', amount: '30g', note: '只取嫩叶' },
          { name: '婴儿米粉', amount: '1勺', note: '' },
        ],
        steps: [
          { step: 1, action: '菠菜焯水1分钟去除草酸，捞出', time: 2, tools: ['锅'], note: '草酸会影响钙铁吸收' },
          { step: 2, action: '菠菜加少量水打成细腻泥', time: 2, tools: ['搅拌机'], note: '' },
          { step: 3, action: '米粉冲调，拌入菠菜泥', time: 2, tools: [], note: '' },
        ],
        nutrition_tips: '植物铁与维生素C一起吃可提高吸收率',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify(['菠菜一定要焯水去草酸', '搭配富含维生素C的食物促进铁吸收']),
      tags: JSON.stringify(['辅食', '菠菜', '6个月', '补铁']),
      is_active: true,
    },
    {
      id: 'baby_006',
      name: '梨子泥',
      name_en: 'Pear Puree',
      type: 'baby',
      category: JSON.stringify(['辅食', '水果']),
      prep_time: 5,
      cook_time: 5,
      total_time: 10,
      difficulty: '简单',
      servings: '1份',
      stage: '6-8m',
      first_intro: true,
      key_nutrients: JSON.stringify(['维生素C', '膳食纤维', '水分']),
      scene_tags: JSON.stringify(['日常', '首次引入', '生病']),
      texture_level: 'puree',
      adult_version: JSON.stringify({
        ingredients: [{ name: '梨', amount: '1个', note: '' }],
        steps: [{ step: 1, action: '梨洗净去核直接食用或做汤', time: 2, tools: [], note: '' }],
        seasonings: [],
      }),
      baby_version: JSON.stringify({
        age_range: '6-8个月',
        ingredients: [{ name: '梨', amount: '半个', note: '去皮去核' }],
        steps: [
          { step: 1, action: '梨去皮去核，蒸5分钟', time: 5, tools: ['蒸锅'], note: '蒸过更容易消化' },
          { step: 2, action: '打成细腻泥状', time: 2, tools: ['搅拌机'], note: '' },
        ],
        nutrition_tips: '梨性凉润燥，适合秋冬季节；水分充足，有助于宝宝补水',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify(['感冒咳嗽期间可多吃梨', '选择成熟软梨更甜']),
      tags: JSON.stringify(['辅食', '梨', '6个月', '水果泥']),
      is_active: true,
    },
    {
      id: 'baby_007',
      name: '土豆泥',
      name_en: 'Mashed Potato',
      type: 'baby',
      category: JSON.stringify(['辅食', '泥糊']),
      prep_time: 5,
      cook_time: 20,
      total_time: 25,
      difficulty: '简单',
      servings: '1份',
      stage: '6-8m',
      first_intro: true,
      key_nutrients: JSON.stringify(['钾', '维生素C', '碳水化合物']),
      scene_tags: JSON.stringify(['日常', '首次引入']),
      texture_level: 'puree',
      adult_version: JSON.stringify({
        ingredients: [{ name: '土豆', amount: '200g', note: '' }],
        steps: [{ step: 1, action: '土豆蒸熟压泥，加黄油牛奶调味', time: 20, tools: ['蒸锅'], note: '' }],
        seasonings: [{ name: '黄油', amount: '1小块' }, { name: '盐', amount: '少量' }],
      }),
      baby_version: JSON.stringify({
        age_range: '6-8个月',
        ingredients: [{ name: '土豆', amount: '50g', note: '去皮' }],
        steps: [
          { step: 1, action: '土豆去皮切块，蒸20分钟至完全软烂', time: 20, tools: ['蒸锅'], note: '' },
          { step: 2, action: '压成细腻泥，加母乳或配方奶调稀', time: 3, tools: [], note: '不加盐' },
        ],
        nutrition_tips: '提供能量和钾，有助于肌肉和心脏功能',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify(['土豆蒸比煮更能保留营养', '注意发芽土豆不能食用']),
      tags: JSON.stringify(['辅食', '土豆', '6个月', '泥糊']),
      is_active: true,
    },
    {
      id: 'baby_008',
      name: '香蕉泥',
      name_en: 'Banana Puree',
      type: 'baby',
      category: JSON.stringify(['辅食', '水果']),
      prep_time: 2,
      cook_time: 0,
      total_time: 2,
      difficulty: '简单',
      servings: '1份',
      stage: '6-8m',
      first_intro: true,
      key_nutrients: JSON.stringify(['钾', '维生素B6', '碳水化合物']),
      scene_tags: JSON.stringify(['日常', '首次引入', '快手']),
      texture_level: 'puree',
      adult_version: JSON.stringify({
        ingredients: [{ name: '香蕉', amount: '1根', note: '' }],
        steps: [{ step: 1, action: '香蕉剥皮直接食用', time: 1, tools: [], note: '' }],
        seasonings: [],
      }),
      baby_version: JSON.stringify({
        age_range: '6-8个月',
        ingredients: [{ name: '香蕉', amount: '1/4根', note: '成熟' }],
        steps: [
          { step: 1, action: '选择成熟香蕉，用勺子压成泥', time: 2, tools: ['勺子'], note: '无需加热' },
        ],
        nutrition_tips: '天然甜味宝宝接受度高，钾含量丰富',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify(['选熟透的香蕉，斑点越多越甜', '香蕉泥氧化快，现做现吃']),
      tags: JSON.stringify(['辅食', '香蕉', '6个月', '快手']),
      is_active: true,
    },

    // ===== 8-10m 辅食早期（细腻糊状）=====
    {
      id: 'baby_009',
      name: '蛋黄南瓜粥',
      name_en: 'Egg Yolk Pumpkin Porridge',
      type: 'baby',
      category: JSON.stringify(['辅食', '粥']),
      prep_time: 5,
      cook_time: 20,
      total_time: 25,
      difficulty: '简单',
      servings: '1份',
      stage: '8-10m',
      first_intro: false,
      key_nutrients: JSON.stringify(['铁', 'DHA', '蛋白质', '维生素A']),
      scene_tags: JSON.stringify(['日常', '补铁']),
      texture_level: 'mash',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '南瓜', amount: '100g', note: '' },
          { name: '大米', amount: '50g', note: '' },
          { name: '鸡蛋', amount: '1个', note: '' },
        ],
        steps: [
          { step: 1, action: '大米煮粥，南瓜切丁加入同煮', time: 20, tools: ['锅'], note: '' },
          { step: 2, action: '打入鸡蛋搅散，煮熟，加盐调味', time: 3, tools: [], note: '' },
        ],
        seasonings: [{ name: '盐', amount: '少量' }],
      }),
      baby_version: JSON.stringify({
        age_range: '8-10个月',
        ingredients: [
          { name: '蛋黄', amount: '1个', note: '' },
          { name: '南瓜', amount: '30g', note: '蒸熟压泥' },
          { name: '稠粥', amount: '3勺', note: '' },
        ],
        steps: [
          { step: 1, action: '蛋黄蒸熟或水煮熟，取出压碎', time: 10, tools: [], note: '从1/4个开始引入' },
          { step: 2, action: '南瓜蒸熟压泥，与稠粥和蛋黄碎混合', time: 3, tools: [], note: '' },
        ],
        nutrition_tips: '蛋黄含DHA促进脑发育，铁含量丰富',
        allergy_alert: '蛋黄为常见过敏原，首次引入需观察3天',
      }),
      cooking_tips: JSON.stringify(['蛋黄首次引入从少量开始', '8-10月龄只引入蛋黄，不引入蛋白']),
      tags: JSON.stringify(['辅食', '蛋黄', '8个月', '补铁', '粥']),
      is_active: true,
    },
    {
      id: 'baby_010',
      name: '猪肝泥',
      name_en: 'Pork Liver Puree',
      type: 'baby',
      category: JSON.stringify(['辅食', '肉泥']),
      prep_time: 10,
      cook_time: 15,
      total_time: 25,
      difficulty: '中等',
      servings: '2份',
      stage: '8-10m',
      first_intro: false,
      key_nutrients: JSON.stringify(['铁', '锌', '维生素A', '维生素B12']),
      scene_tags: JSON.stringify(['日常', '补铁']),
      texture_level: 'mash',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '猪肝', amount: '150g', note: '' },
          { name: '姜片', amount: '3片', note: '' },
        ],
        steps: [
          { step: 1, action: '猪肝浸泡1小时换水去血水', time: 60, tools: [], note: '' },
          { step: 2, action: '加姜片水煮至熟透，切片食用', time: 15, tools: ['锅'], note: '' },
        ],
        seasonings: [{ name: '酱油', amount: '少量' }, { name: '盐', amount: '少量' }],
      }),
      baby_version: JSON.stringify({
        age_range: '8-10个月',
        ingredients: [
          { name: '猪肝', amount: '30g', note: '新鲜' },
        ],
        steps: [
          { step: 1, action: '猪肝浸泡30分钟，换水去除血水', time: 30, tools: [], note: '去腥很重要' },
          { step: 2, action: '猪肝蒸15分钟至完全熟透', time: 15, tools: ['蒸锅'], note: '确保中心熟透' },
          { step: 3, action: '用搅拌机加少量温水打成细腻泥', time: 3, tools: ['搅拌机'], note: '' },
        ],
        nutrition_tips: '猪肝是补铁神器，每周1-2次即可，不宜过多',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify(['选购新鲜猪肝，不买颜色发灰的', '每周喂1-2次，不可过量']),
      tags: JSON.stringify(['辅食', '猪肝', '8个月', '补铁']),
      is_active: true,
    },
    {
      id: 'baby_011',
      name: '豆腐蛋黄羹',
      name_en: 'Tofu Egg Yolk Custard',
      type: 'baby',
      category: JSON.stringify(['辅食', '蒸蛋']),
      prep_time: 5,
      cook_time: 10,
      total_time: 15,
      difficulty: '简单',
      servings: '1份',
      stage: '8-10m',
      first_intro: false,
      key_nutrients: JSON.stringify(['蛋白质', '钙', '铁', 'DHA']),
      scene_tags: JSON.stringify(['日常', '快手']),
      texture_level: 'mash',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '豆腐', amount: '100g', note: '' },
          { name: '鸡蛋', amount: '1个', note: '' },
        ],
        steps: [
          { step: 1, action: '豆腐切丁，鸡蛋打散混合蒸10分钟', time: 10, tools: ['蒸锅'], note: '' },
        ],
        seasonings: [{ name: '盐', amount: '少量' }, { name: '生抽', amount: '少量' }],
      }),
      baby_version: JSON.stringify({
        age_range: '8-10个月',
        ingredients: [
          { name: '嫩豆腐', amount: '50g', note: '' },
          { name: '蛋黄', amount: '1个', note: '' },
          { name: '温水', amount: '30ml', note: '' },
        ],
        steps: [
          { step: 1, action: '蛋黄加温水打散过滤', time: 3, tools: [], note: '过滤去除气泡' },
          { step: 2, action: '豆腐压碎加入蛋黄液，蒸10分钟', time: 10, tools: ['蒸锅'], note: '小火蒸避免起泡' },
        ],
        nutrition_tips: '豆腐补钙，蛋黄补铁补DHA，营养全面',
        allergy_alert: '豆类可能过敏，首次引入观察',
      }),
      cooking_tips: JSON.stringify(['嫩豆腐口感更适合小月龄', '蒸时加盖防止水汽滴落']),
      tags: JSON.stringify(['辅食', '豆腐', '蛋黄', '8个月']),
      is_active: true,
    },
    {
      id: 'baby_012',
      name: '鱼泥粥',
      name_en: 'Fish Puree Congee',
      type: 'baby',
      category: JSON.stringify(['辅食', '粥']),
      prep_time: 10,
      cook_time: 20,
      total_time: 30,
      difficulty: '中等',
      servings: '1份',
      stage: '8-10m',
      first_intro: false,
      key_nutrients: JSON.stringify(['DHA', '蛋白质', '锌', 'Omega-3']),
      scene_tags: JSON.stringify(['日常', '补脑']),
      texture_level: 'mash',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '鲈鱼', amount: '150g', note: '' },
          { name: '大米', amount: '50g', note: '' },
        ],
        steps: [
          { step: 1, action: '大米煮粥，鱼蒸熟去刺', time: 20, tools: ['锅', '蒸锅'], note: '' },
          { step: 2, action: '鱼肉切碎加入粥中，调味', time: 3, tools: [], note: '' },
        ],
        seasonings: [{ name: '盐', amount: '少量' }, { name: '姜', amount: '2片' }],
      }),
      baby_version: JSON.stringify({
        age_range: '8-10个月',
        ingredients: [
          { name: '鲈鱼/鳕鱼', amount: '30g', note: '刺少的白身鱼' },
          { name: '稠粥', amount: '3勺', note: '' },
        ],
        steps: [
          { step: 1, action: '鱼肉蒸熟，仔细去除所有鱼刺', time: 10, tools: ['蒸锅'], note: '去刺要非常仔细' },
          { step: 2, action: '鱼肉压成泥，拌入稠粥', time: 3, tools: [], note: '' },
        ],
        nutrition_tips: 'DHA促进大脑和视网膜发育，选择刺少的白身鱼',
        allergy_alert: '海鱼为过敏原，首次引入需谨慎观察',
      }),
      cooking_tips: JSON.stringify(['选鳕鱼、鲈鱼等刺少的鱼', '去刺要极其仔细，用手摸确认']),
      tags: JSON.stringify(['辅食', '鱼', '8个月', 'DHA', '补脑']),
      is_active: true,
    },
    {
      id: 'baby_013',
      name: '猪肉泥菠菜粥',
      name_en: 'Pork Spinach Congee',
      type: 'baby',
      category: JSON.stringify(['辅食', '粥']),
      prep_time: 10,
      cook_time: 25,
      total_time: 35,
      difficulty: '中等',
      servings: '1份',
      stage: '8-10m',
      first_intro: false,
      key_nutrients: JSON.stringify(['铁', '蛋白质', '叶酸', '锌']),
      scene_tags: JSON.stringify(['日常', '补铁']),
      texture_level: 'mash',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '猪瘦肉', amount: '100g', note: '' },
          { name: '菠菜', amount: '50g', note: '' },
        ],
        steps: [
          { step: 1, action: '猪肉切片炒熟，菠菜焯水切碎混合', time: 10, tools: ['锅'], note: '' },
        ],
        seasonings: [{ name: '盐', amount: '少量' }, { name: '酱油', amount: '少量' }],
      }),
      baby_version: JSON.stringify({
        age_range: '8-10个月',
        ingredients: [
          { name: '猪瘦肉', amount: '20g', note: '' },
          { name: '菠菜叶', amount: '20g', note: '' },
          { name: '稠粥', amount: '3勺', note: '' },
        ],
        steps: [
          { step: 1, action: '猪肉蒸熟后用搅拌机打成泥', time: 15, tools: ['蒸锅', '搅拌机'], note: '' },
          { step: 2, action: '菠菜焯水去草酸，打成泥', time: 5, tools: [], note: '' },
          { step: 3, action: '肉泥和菠菜泥拌入稠粥', time: 2, tools: [], note: '' },
        ],
        nutrition_tips: '肉类铁吸收率高于植物铁，菠菜叶酸丰富',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify(['猪肉选瘦肉，避免过多脂肪', '菠菜必须焯水去除草酸']),
      tags: JSON.stringify(['辅食', '猪肉', '菠菜', '8个月', '补铁']),
      is_active: true,
    },
    {
      id: 'baby_014',
      name: '软烂小米粥',
      name_en: 'Soft Millet Congee',
      type: 'baby',
      category: JSON.stringify(['辅食', '粥']),
      prep_time: 5,
      cook_time: 30,
      total_time: 35,
      difficulty: '简单',
      servings: '2份',
      stage: '8-10m',
      first_intro: false,
      key_nutrients: JSON.stringify(['铁', '维生素B1', '锌']),
      scene_tags: JSON.stringify(['日常', '生病']),
      texture_level: 'mash',
      adult_version: JSON.stringify({
        ingredients: [{ name: '小米', amount: '50g', note: '' }],
        steps: [{ step: 1, action: '小米加水大火烧开转小火熬30分钟', time: 30, tools: ['锅'], note: '' }],
        seasonings: [],
      }),
      baby_version: JSON.stringify({
        age_range: '8-10个月',
        ingredients: [{ name: '小米', amount: '30g', note: '' }],
        steps: [
          { step: 1, action: '小米洗净加5倍水煮30分钟', time: 30, tools: ['锅'], note: '要非常软烂' },
          { step: 2, action: '取上层米油给宝宝', time: 2, tools: [], note: '米油营养丰富易消化' },
        ],
        nutrition_tips: '小米富含铁和B族维生素，温补脾胃，适合生病期间',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify(['小米不需要提前浸泡', '加水多一点更软烂，适合小宝宝']),
      tags: JSON.stringify(['辅食', '小米', '8个月', '生病']),
      is_active: true,
    },
    {
      id: 'baby_015',
      name: '西兰花豆腐泥',
      name_en: 'Broccoli Tofu Puree',
      type: 'baby',
      category: JSON.stringify(['辅食', '蔬菜']),
      prep_time: 5,
      cook_time: 10,
      total_time: 15,
      difficulty: '简单',
      servings: '1份',
      stage: '8-10m',
      first_intro: false,
      key_nutrients: JSON.stringify(['钙', '维生素C', '蛋白质', '叶酸']),
      scene_tags: JSON.stringify(['日常', '补钙']),
      texture_level: 'mash',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '西兰花', amount: '150g', note: '' },
          { name: '豆腐', amount: '100g', note: '' },
        ],
        steps: [
          { step: 1, action: '西兰花焯水，豆腐切块，混合翻炒', time: 10, tools: ['锅'], note: '' },
        ],
        seasonings: [{ name: '盐', amount: '少量' }, { name: '蒜', amount: '2瓣' }],
      }),
      baby_version: JSON.stringify({
        age_range: '8-10个月',
        ingredients: [
          { name: '西兰花', amount: '30g', note: '只取花球' },
          { name: '嫩豆腐', amount: '30g', note: '' },
        ],
        steps: [
          { step: 1, action: '西兰花焯水3分钟至软，只取花球', time: 5, tools: ['锅'], note: '' },
          { step: 2, action: '与豆腐一起打成细腻泥', time: 3, tools: ['搅拌机'], note: '' },
        ],
        nutrition_tips: '西兰花维生素C丰富，豆腐补钙，两者搭配营养全面',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify(['西兰花茎部较硬，宝宝版只取花球', '豆腐选嫩豆腐更好打泥']),
      tags: JSON.stringify(['辅食', '西兰花', '豆腐', '8个月', '补钙']),
      is_active: true,
    },
    {
      id: 'baby_016',
      name: '鸡肉蔬菜烂面条',
      name_en: 'Chicken Vegetable Soft Noodles',
      type: 'baby',
      category: JSON.stringify(['辅食', '面条']),
      prep_time: 5,
      cook_time: 15,
      total_time: 20,
      difficulty: '简单',
      servings: '1份',
      stage: '8-10m',
      first_intro: false,
      key_nutrients: JSON.stringify(['蛋白质', '铁', '维生素B', '碳水化合物']),
      scene_tags: JSON.stringify(['日常', '快手']),
      texture_level: 'mash',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '面条', amount: '100g', note: '' },
          { name: '鸡胸肉', amount: '50g', note: '' },
        ],
        steps: [
          { step: 1, action: '面条煮熟，鸡肉切片炒熟混合', time: 15, tools: ['锅'], note: '' },
        ],
        seasonings: [{ name: '盐', amount: '少量' }],
      }),
      baby_version: JSON.stringify({
        age_range: '8-10个月',
        ingredients: [
          { name: '婴儿细面条', amount: '20g', note: '' },
          { name: '鸡胸肉', amount: '15g', note: '' },
          { name: '胡萝卜', amount: '10g', note: '' },
        ],
        steps: [
          { step: 1, action: '鸡肉蒸熟打成肉泥', time: 15, tools: ['蒸锅'], note: '' },
          { step: 2, action: '细面条折短，加胡萝卜碎煮到极烂', time: 10, tools: ['锅'], note: '比普通面条多煮5分钟' },
          { step: 3, action: '拌入鸡肉泥', time: 1, tools: [], note: '' },
        ],
        nutrition_tips: '面条提供能量，鸡肉补充蛋白质，适合正在学咀嚼的宝宝',
        allergy_alert: '注意面条含麸质',
      }),
      cooking_tips: JSON.stringify(['选婴儿专用细面条更容易煮烂', '可加少量芝麻油增加香味']),
      tags: JSON.stringify(['辅食', '面条', '鸡肉', '8个月']),
      is_active: true,
    },

    // ===== 10-12m 辅食中期（细碎状）=====
    {
      id: 'baby_017',
      name: '全蛋蒸蛋羹',
      name_en: 'Steamed Egg Custard',
      type: 'baby',
      category: JSON.stringify(['辅食', '蒸蛋']),
      prep_time: 5,
      cook_time: 10,
      total_time: 15,
      difficulty: '简单',
      servings: '1份',
      stage: '10-12m',
      first_intro: false,
      key_nutrients: JSON.stringify(['蛋白质', '卵磷脂', 'DHA', '维生素D']),
      scene_tags: JSON.stringify(['日常', '快手']),
      texture_level: 'minced',
      adult_version: JSON.stringify({
        ingredients: [{ name: '鸡蛋', amount: '2个', note: '' }],
        steps: [
          { step: 1, action: '鸡蛋打散，加盐和温水1:1.5，蒸10分钟', time: 10, tools: ['蒸锅'], note: '' },
        ],
        seasonings: [{ name: '盐', amount: '少量' }, { name: '生抽', amount: '少量' }],
      }),
      baby_version: JSON.stringify({
        age_range: '10-12个月',
        ingredients: [
          { name: '全蛋', amount: '1个', note: '' },
          { name: '温水', amount: '60ml', note: '约鸡蛋体积1.5倍' },
        ],
        steps: [
          { step: 1, action: '鸡蛋打散，加温水搅拌均匀后过筛', time: 3, tools: [], note: '过筛口感更嫩滑' },
          { step: 2, action: '盖保鲜膜或盖子，小火蒸8-10分钟', time: 10, tools: ['蒸锅'], note: '不加任何调料' },
        ],
        nutrition_tips: '全蛋蛋白质利用率高，卵磷脂促进大脑发育',
        allergy_alert: '10月龄后引入蛋白，首次观察有无过敏',
      }),
      cooking_tips: JSON.stringify(['蒸蛋比例鸡蛋:水=1:1.5', '小火蒸避免起泡，口感更嫩']),
      tags: JSON.stringify(['辅食', '鸡蛋', '10个月', '蒸蛋']),
      is_active: true,
    },
    {
      id: 'baby_018',
      name: '虾仁豆腐软饭',
      name_en: 'Shrimp Tofu Soft Rice',
      type: 'baby',
      category: JSON.stringify(['辅食', '软饭']),
      prep_time: 10,
      cook_time: 15,
      total_time: 25,
      difficulty: '中等',
      servings: '1份',
      stage: '10-12m',
      first_intro: false,
      key_nutrients: JSON.stringify(['蛋白质', '钙', 'DHA', '锌']),
      scene_tags: JSON.stringify(['日常']),
      texture_level: 'minced',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '虾仁', amount: '100g', note: '' },
          { name: '豆腐', amount: '100g', note: '' },
        ],
        steps: [
          { step: 1, action: '虾仁豆腐翻炒，加蒜末和盐调味', time: 10, tools: ['锅'], note: '' },
        ],
        seasonings: [{ name: '盐', amount: '少量' }, { name: '蒜', amount: '2瓣' }],
      }),
      baby_version: JSON.stringify({
        age_range: '10-12个月',
        ingredients: [
          { name: '鲜虾仁', amount: '3-4只', note: '去壳去虾线' },
          { name: '嫩豆腐', amount: '30g', note: '' },
          { name: '软饭', amount: '半碗', note: '比正常饭多加水' },
        ],
        steps: [
          { step: 1, action: '虾仁蒸熟，切成小碎粒', time: 8, tools: ['蒸锅'], note: '确保熟透' },
          { step: 2, action: '豆腐压碎，与虾粒混合拌入软饭', time: 3, tools: [], note: '' },
        ],
        nutrition_tips: '虾仁富含优质蛋白和钙，豆腐补充钙质，促进骨骼发育',
        allergy_alert: '虾为常见过敏原，首次引入需谨慎观察',
      }),
      cooking_tips: JSON.stringify(['虾仁选新鲜的，冷冻虾解冻后也可', '软饭加水量是正常米饭的1.5倍']),
      tags: JSON.stringify(['辅食', '虾', '豆腐', '10个月']),
      is_active: true,
    },
    {
      id: 'baby_019',
      name: '番茄鸡蛋软饭',
      name_en: 'Tomato Egg Soft Rice',
      type: 'baby',
      category: JSON.stringify(['辅食', '软饭']),
      prep_time: 5,
      cook_time: 15,
      total_time: 20,
      difficulty: '简单',
      servings: '1份',
      stage: '10-12m',
      first_intro: false,
      key_nutrients: JSON.stringify(['维生素C', '蛋白质', '番茄红素', '铁']),
      scene_tags: JSON.stringify(['日常', '快手']),
      texture_level: 'minced',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '番茄', amount: '2个', note: '' },
          { name: '鸡蛋', amount: '2个', note: '' },
        ],
        steps: [
          { step: 1, action: '鸡蛋炒散，番茄切块翻炒，加盐调味', time: 10, tools: ['锅'], note: '' },
        ],
        seasonings: [{ name: '盐', amount: '少量' }, { name: '糖', amount: '少量' }],
      }),
      baby_version: JSON.stringify({
        age_range: '10-12个月',
        ingredients: [
          { name: '番茄', amount: '半个', note: '' },
          { name: '鸡蛋', amount: '1个', note: '' },
          { name: '软饭', amount: '半碗', note: '' },
        ],
        steps: [
          { step: 1, action: '番茄去皮去籽切小丁', time: 3, tools: [], note: '' },
          { step: 2, action: '鸡蛋打散，无油炒熟切碎', time: 5, tools: ['锅'], note: '尽量不加油或少油' },
          { step: 3, action: '番茄丁炒软，与鸡蛋碎拌入软饭', time: 5, tools: [], note: '' },
        ],
        nutrition_tips: '番茄红素抗氧化，维生素C促进铁吸收',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify(['番茄去皮给宝宝更好消化', '不加盐不加糖，保留原味']),
      tags: JSON.stringify(['辅食', '番茄', '鸡蛋', '10个月']),
      is_active: true,
    },
    {
      id: 'baby_020',
      name: '牛肉蔬菜粥',
      name_en: 'Beef Vegetable Congee',
      type: 'baby',
      category: JSON.stringify(['辅食', '粥']),
      prep_time: 10,
      cook_time: 30,
      total_time: 40,
      difficulty: '中等',
      servings: '2份',
      stage: '10-12m',
      first_intro: false,
      key_nutrients: JSON.stringify(['铁', '锌', '蛋白质', '维生素B12']),
      scene_tags: JSON.stringify(['日常', '补铁']),
      texture_level: 'minced',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '牛肉', amount: '150g', note: '' },
          { name: '大米', amount: '50g', note: '' },
        ],
        steps: [
          { step: 1, action: '牛肉切片，大米煮粥，牛肉加入粥中煮熟', time: 30, tools: ['锅'], note: '' },
        ],
        seasonings: [{ name: '盐', amount: '少量' }, { name: '姜', amount: '2片' }],
      }),
      baby_version: JSON.stringify({
        age_range: '10-12个月',
        ingredients: [
          { name: '牛里脊', amount: '25g', note: '选嫩的部位' },
          { name: '大米', amount: '30g', note: '' },
          { name: '胡萝卜', amount: '15g', note: '' },
        ],
        steps: [
          { step: 1, action: '牛肉蒸熟，用搅拌机打成肉碎（3-4mm）', time: 15, tools: ['蒸锅', '搅拌机'], note: '' },
          { step: 2, action: '大米和胡萝卜碎熬粥30分钟', time: 30, tools: ['锅'], note: '' },
          { step: 3, action: '牛肉碎拌入粥中', time: 2, tools: [], note: '' },
        ],
        nutrition_tips: '牛肉血红素铁含量丰富，比猪肉锌含量更高',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify(['牛里脊肉质嫩，打碎后口感好', '可批量蒸牛肉打泥冷冻备用']),
      tags: JSON.stringify(['辅食', '牛肉', '10个月', '补铁', '粥']),
      is_active: true,
    },
    {
      id: 'baby_021',
      name: '三文鱼南瓜软饭',
      name_en: 'Salmon Pumpkin Soft Rice',
      type: 'baby',
      category: JSON.stringify(['辅食', '软饭']),
      prep_time: 5,
      cook_time: 15,
      total_time: 20,
      difficulty: '简单',
      servings: '1份',
      stage: '10-12m',
      first_intro: false,
      key_nutrients: JSON.stringify(['DHA', 'Omega-3', '蛋白质', '维生素A']),
      scene_tags: JSON.stringify(['日常', '补脑']),
      texture_level: 'minced',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '三文鱼', amount: '150g', note: '' },
          { name: '南瓜', amount: '100g', note: '' },
        ],
        steps: [
          { step: 1, action: '三文鱼煎熟，南瓜蒸熟，搭配食用', time: 15, tools: ['锅'], note: '' },
        ],
        seasonings: [{ name: '盐', amount: '少量' }, { name: '黑胡椒', amount: '少量' }],
      }),
      baby_version: JSON.stringify({
        age_range: '10-12个月',
        ingredients: [
          { name: '三文鱼', amount: '25g', note: '去皮去骨' },
          { name: '南瓜泥', amount: '30g', note: '蒸熟压泥' },
          { name: '软饭', amount: '半碗', note: '' },
        ],
        steps: [
          { step: 1, action: '三文鱼蒸10分钟，去皮去刺，压成碎', time: 12, tools: ['蒸锅'], note: '' },
          { step: 2, action: '南瓜蒸熟压泥，与三文鱼碎拌入软饭', time: 5, tools: [], note: '' },
        ],
        nutrition_tips: '三文鱼DHA含量丰富，是脑发育黄金营养素',
        allergy_alert: '海鱼过敏者慎用',
      }),
      cooking_tips: JSON.stringify(['三文鱼一定蒸熟不能生食', '选择新鲜的或冷冻解冻的']),
      tags: JSON.stringify(['辅食', '三文鱼', 'DHA', '10个月', '补脑']),
      is_active: true,
    },
    {
      id: 'baby_022',
      name: '蔬菜鸡蛋饼',
      name_en: 'Vegetable Egg Pancake',
      type: 'baby',
      category: JSON.stringify(['辅食', '手指食物']),
      prep_time: 5,
      cook_time: 10,
      total_time: 15,
      difficulty: '简单',
      servings: '2份',
      stage: '10-12m',
      first_intro: false,
      key_nutrients: JSON.stringify(['蛋白质', '维生素C', '钙', '铁']),
      scene_tags: JSON.stringify(['日常', '快手', '手指食物']),
      texture_level: 'minced',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '鸡蛋', amount: '2个', note: '' },
          { name: '西葫芦', amount: '100g', note: '' },
          { name: '面粉', amount: '2勺', note: '' },
        ],
        steps: [
          { step: 1, action: '西葫芦擦丝，与鸡蛋面粉混合，煎饼', time: 10, tools: ['平底锅'], note: '' },
        ],
        seasonings: [{ name: '盐', amount: '少量' }],
      }),
      baby_version: JSON.stringify({
        age_range: '10-12个月',
        ingredients: [
          { name: '鸡蛋', amount: '1个', note: '' },
          { name: '西葫芦', amount: '30g', note: '擦细丝' },
          { name: '面粉', amount: '1小勺', note: '' },
        ],
        steps: [
          { step: 1, action: '西葫芦擦细丝，与鸡蛋和面粉混合成糊', time: 3, tools: [], note: '' },
          { step: 2, action: '平底锅薄薄刷油，小火煎至两面熟', time: 8, tools: ['平底锅'], note: '做薄一点更容易熟透' },
          { step: 3, action: '切成宝宝方便拿的小条', time: 2, tools: [], note: '' },
        ],
        nutrition_tips: '手指食物训练精细动作，鼓励自主进食',
        allergy_alert: '含麸质，首次引入观察',
      }),
      cooking_tips: JSON.stringify(['不加盐让宝宝品尝原味', '切成长条更方便宝宝抓握']),
      tags: JSON.stringify(['辅食', '手指食物', '蛋饼', '10个月']),
      is_active: true,
    },

    // ===== 12-18m 辅食后期（接近成人软食）=====
    {
      id: 'baby_023',
      name: '宝宝版番茄牛肉面',
      name_en: 'Baby Tomato Beef Noodles',
      type: 'baby',
      category: JSON.stringify(['辅食', '面条']),
      prep_time: 10,
      cook_time: 20,
      total_time: 30,
      difficulty: '中等',
      servings: '1份',
      stage: '12-18m',
      first_intro: false,
      key_nutrients: JSON.stringify(['铁', '蛋白质', '番茄红素', '维生素C']),
      scene_tags: JSON.stringify(['日常']),
      texture_level: 'chunks',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '番茄', amount: '2个', note: '' },
          { name: '牛肉', amount: '150g', note: '' },
          { name: '面条', amount: '200g', note: '' },
        ],
        steps: [
          { step: 1, action: '牛肉切块炖软，番茄切块炒出汁，加面条煮熟', time: 30, tools: ['锅'], note: '' },
        ],
        seasonings: [{ name: '盐', amount: '少量' }, { name: '生抽', amount: '少量' }],
      }),
      baby_version: JSON.stringify({
        age_range: '12-18个月',
        ingredients: [
          { name: '牛肉末', amount: '25g', note: '' },
          { name: '番茄', amount: '半个', note: '' },
          { name: '细面条', amount: '30g', note: '折短' },
        ],
        steps: [
          { step: 1, action: '牛肉末不加油翻炒至变色', time: 5, tools: ['锅'], note: '' },
          { step: 2, action: '番茄去皮切小丁加入，翻炒出汁', time: 5, tools: [], note: '' },
          { step: 3, action: '加水煮沸，下面条煮烂约10分钟', time: 10, tools: [], note: '比平时多煮5分钟' },
        ],
        nutrition_tips: '番茄维生素C促进牛肉铁的吸收，一举两得',
        allergy_alert: '含麸质',
      }),
      cooking_tips: JSON.stringify(['可加少量酱油（约2-3滴）提鲜', '牛肉末比块状更易熟、易嚼']),
      tags: JSON.stringify(['辅食', '牛肉', '番茄', '12个月', '面条']),
      is_active: true,
    },
    {
      id: 'baby_024',
      name: '宝宝版蛋炒饭',
      name_en: 'Baby Egg Fried Rice',
      type: 'baby',
      category: JSON.stringify(['辅食', '米饭']),
      prep_time: 5,
      cook_time: 10,
      total_time: 15,
      difficulty: '简单',
      servings: '1份',
      stage: '12-18m',
      first_intro: false,
      key_nutrients: JSON.stringify(['蛋白质', '碳水化合物', '卵磷脂', '维生素A']),
      scene_tags: JSON.stringify(['日常', '快手']),
      texture_level: 'chunks',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '米饭', amount: '1碗', note: '' },
          { name: '鸡蛋', amount: '2个', note: '' },
        ],
        steps: [
          { step: 1, action: '热锅冷油，炒散鸡蛋，加米饭大火翻炒，加盐', time: 8, tools: ['锅'], note: '' },
        ],
        seasonings: [{ name: '盐', amount: '少量' }, { name: '葱', amount: '少量' }],
      }),
      baby_version: JSON.stringify({
        age_range: '12-18个月',
        ingredients: [
          { name: '软饭', amount: '半碗', note: '比正常饭软' },
          { name: '鸡蛋', amount: '1个', note: '' },
          { name: '胡萝卜', amount: '10g', note: '煮软切小丁' },
        ],
        steps: [
          { step: 1, action: '鸡蛋打散，少油炒熟碎', time: 3, tools: ['锅'], note: '' },
          { step: 2, action: '加入软饭和胡萝卜小丁翻炒均匀', time: 5, tools: [], note: '不加盐' },
        ],
        nutrition_tips: '简单易做，让宝宝练习用勺子自主进食',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify(['软饭比干饭更适合12-18月宝宝', '胡萝卜要提前煮软再切丁']),
      tags: JSON.stringify(['辅食', '蛋炒饭', '12个月', '快手']),
      is_active: true,
    },
    {
      id: 'baby_025',
      name: '清蒸鳕鱼配菜泥',
      name_en: 'Steamed Cod with Vegetable Puree',
      type: 'baby',
      category: JSON.stringify(['辅食', '鱼']),
      prep_time: 5,
      cook_time: 12,
      total_time: 17,
      difficulty: '简单',
      servings: '1份',
      stage: '12-18m',
      first_intro: false,
      key_nutrients: JSON.stringify(['DHA', '蛋白质', 'Omega-3', '维生素D']),
      scene_tags: JSON.stringify(['日常', '补脑']),
      texture_level: 'chunks',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '鳕鱼', amount: '200g', note: '' },
          { name: '姜丝', amount: '少量', note: '' },
        ],
        steps: [
          { step: 1, action: '鳕鱼蒸12分钟，加姜丝生抽', time: 12, tools: ['蒸锅'], note: '' },
        ],
        seasonings: [{ name: '生抽', amount: '1勺' }, { name: '芝麻油', amount: '少量' }],
      }),
      baby_version: JSON.stringify({
        age_range: '12-18个月',
        ingredients: [
          { name: '鳕鱼', amount: '40g', note: '去皮去骨' },
          { name: '土豆泥', amount: '30g', note: '' },
        ],
        steps: [
          { step: 1, action: '鳕鱼蒸12分钟，去皮去刺，切成小块', time: 15, tools: ['蒸锅'], note: '' },
          { step: 2, action: '搭配土豆泥一起食用', time: 2, tools: [], note: '' },
        ],
        nutrition_tips: '鳕鱼DHA含量高，刺少好处理，适合宝宝',
        allergy_alert: '海鱼过敏者慎用',
      }),
      cooking_tips: JSON.stringify(['鳕鱼选银鳕鱼或大西洋鳕鱼，刺最少', '12月后可加极少量生抽']),
      tags: JSON.stringify(['辅食', '鳕鱼', '12个月', 'DHA']),
      is_active: true,
    },
    {
      id: 'baby_026',
      name: '宝宝馄饨',
      name_en: 'Baby Wonton',
      type: 'baby',
      category: JSON.stringify(['辅食', '主食']),
      prep_time: 20,
      cook_time: 5,
      total_time: 25,
      difficulty: '中等',
      servings: '2份',
      stage: '12-18m',
      first_intro: false,
      key_nutrients: JSON.stringify(['蛋白质', '铁', '维生素B', '碳水化合物']),
      scene_tags: JSON.stringify(['日常', '节日']),
      texture_level: 'chunks',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '猪肉馅', amount: '150g', note: '' },
          { name: '馄饨皮', amount: '适量', note: '' },
        ],
        steps: [
          { step: 1, action: '肉馅加调料拌匀，包馄饨，煮熟', time: 20, tools: ['锅'], note: '' },
        ],
        seasonings: [{ name: '盐', amount: '少量' }, { name: '酱油', amount: '1勺' }, { name: '姜', amount: '少量' }],
      }),
      baby_version: JSON.stringify({
        age_range: '12-18个月',
        ingredients: [
          { name: '猪肉末', amount: '50g', note: '' },
          { name: '菠菜末', amount: '20g', note: '' },
          { name: '馄饨皮', amount: '10张', note: '薄皮' },
        ],
        steps: [
          { step: 1, action: '肉末加菠菜末混合（不加盐），包成小馄饨', time: 15, tools: [], note: '包小一点方便宝宝' },
          { step: 2, action: '沸水煮3-4分钟至熟', time: 5, tools: ['锅'], note: '' },
        ],
        nutrition_tips: '馄饨营养全面，铁和蛋白质丰富',
        allergy_alert: '含麸质',
      }),
      cooking_tips: JSON.stringify(['馄饨包小一点，1口能吃下最好', '可批量制作冷冻备用']),
      tags: JSON.stringify(['辅食', '馄饨', '12个月', '猪肉']),
      is_active: true,
    },
    {
      id: 'baby_027',
      name: '宝宝三色饭团',
      name_en: 'Baby Three-Color Rice Ball',
      type: 'baby',
      category: JSON.stringify(['辅食', '手指食物']),
      prep_time: 10,
      cook_time: 0,
      total_time: 10,
      difficulty: '简单',
      servings: '3份',
      stage: '12-18m',
      first_intro: false,
      key_nutrients: JSON.stringify(['碳水化合物', '蛋白质', '维生素', '矿物质']),
      scene_tags: JSON.stringify(['日常', '快手', '手指食物']),
      texture_level: 'chunks',
      adult_version: JSON.stringify({
        ingredients: [{ name: '米饭', amount: '1碗', note: '' }],
        steps: [{ step: 1, action: '米饭捏成团，外面包各种食材', time: 10, tools: [], note: '' }],
        seasonings: [{ name: '盐', amount: '少量' }],
      }),
      baby_version: JSON.stringify({
        age_range: '12-18个月',
        ingredients: [
          { name: '软饭', amount: '半碗', note: '' },
          { name: '胡萝卜碎', amount: '10g', note: '煮软' },
          { name: '菠菜碎', amount: '10g', note: '焯水' },
          { name: '蛋黄碎', amount: '1个', note: '煮熟' },
        ],
        steps: [
          { step: 1, action: '软饭分成3份，分别拌入3种不同食材', time: 5, tools: [], note: '' },
          { step: 2, action: '用保鲜膜将每份捏成小球形', time: 5, tools: [], note: '大小适合宝宝一口吃' },
        ],
        nutrition_tips: '颜色丰富增加宝宝对食物的兴趣，多种营养素搭配',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify(['可以根据宝宝喜好换不同食材', '捏紧实一点防止散开']),
      tags: JSON.stringify(['辅食', '饭团', '12个月', '手指食物']),
      is_active: true,
    },
    {
      id: 'baby_028',
      name: '宝宝版红烧豆腐',
      name_en: 'Baby Braised Tofu',
      type: 'baby',
      category: JSON.stringify(['辅食', '豆制品']),
      prep_time: 5,
      cook_time: 10,
      total_time: 15,
      difficulty: '简单',
      servings: '2份',
      stage: '12-18m',
      first_intro: false,
      key_nutrients: JSON.stringify(['钙', '蛋白质', '铁', '大豆异黄酮']),
      scene_tags: JSON.stringify(['日常', '补钙']),
      texture_level: 'chunks',
      adult_version: JSON.stringify({
        ingredients: [{ name: '豆腐', amount: '200g', note: '' }],
        steps: [
          { step: 1, action: '豆腐切块，加酱油番茄汁烧至入味', time: 10, tools: ['锅'], note: '' },
        ],
        seasonings: [{ name: '酱油', amount: '1勺' }, { name: '盐', amount: '少量' }],
      }),
      baby_version: JSON.stringify({
        age_range: '12-18个月',
        ingredients: [
          { name: '北豆腐', amount: '80g', note: '切1cm小块' },
          { name: '番茄', amount: '半个', note: '去皮切小丁' },
        ],
        steps: [
          { step: 1, action: '番茄去皮切丁，小火炒出汁', time: 3, tools: ['锅'], note: '' },
          { step: 2, action: '加入豆腐块，轻翻2分钟，番茄汁包裹豆腐', time: 5, tools: [], note: '动作轻避免豆腐碎' },
        ],
        nutrition_tips: '豆腐是优质植物蛋白和钙的来源，番茄增加维生素C',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify(['北豆腐比嫩豆腐更耐煮不易碎', '不加盐，靠番茄汁的自然酸甜调味']),
      tags: JSON.stringify(['辅食', '豆腐', '12个月', '补钙']),
      is_active: true,
    },

    // ===== 18-24m 幼儿早期 =====
    {
      id: 'baby_029',
      name: '番茄牛肉炖土豆',
      name_en: 'Tomato Beef Potato Stew',
      type: 'baby',
      category: JSON.stringify(['辅食', '炖菜']),
      prep_time: 10,
      cook_time: 40,
      total_time: 50,
      difficulty: '中等',
      servings: '3份',
      stage: '18-24m',
      first_intro: false,
      key_nutrients: JSON.stringify(['铁', '蛋白质', '钾', '维生素C']),
      scene_tags: JSON.stringify(['日常', '节日']),
      texture_level: 'chunks',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '牛肉', amount: '200g', note: '' },
          { name: '土豆', amount: '200g', note: '' },
          { name: '番茄', amount: '2个', note: '' },
        ],
        steps: [
          { step: 1, action: '牛肉切块焯水，番茄炒汁，加土豆炖40分钟', time: 50, tools: ['锅'], note: '' },
        ],
        seasonings: [{ name: '盐', amount: '少量' }, { name: '酱油', amount: '1勺' }],
      }),
      baby_version: JSON.stringify({
        age_range: '18-24个月',
        ingredients: [
          { name: '牛里脊', amount: '40g', note: '' },
          { name: '土豆', amount: '50g', note: '' },
          { name: '番茄', amount: '半个', note: '' },
        ],
        steps: [
          { step: 1, action: '牛肉切小丁，番茄去皮切丁，土豆切小块', time: 8, tools: [], note: '' },
          { step: 2, action: '少油翻炒番茄出汁，加牛肉和土豆', time: 5, tools: ['锅'], note: '' },
          { step: 3, action: '加水没过食材，小火炖30分钟至软烂', time: 30, tools: [], note: '' },
        ],
        nutrition_tips: '番茄维生素C帮助牛肉铁的吸收，土豆提供饱腹感',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify(['可用压力锅缩短时间', '牛肉切小块更快熟']),
      tags: JSON.stringify(['辅食', '牛肉', '番茄', '18个月']),
      is_active: true,
    },
    {
      id: 'baby_030',
      name: '宝宝版鸡蛋羹配菜碎',
      name_en: 'Egg Custard with Veggie Bits',
      type: 'baby',
      category: JSON.stringify(['辅食', '蒸蛋']),
      prep_time: 5,
      cook_time: 10,
      total_time: 15,
      difficulty: '简单',
      servings: '1份',
      stage: '18-24m',
      first_intro: false,
      key_nutrients: JSON.stringify(['蛋白质', '卵磷脂', '钙', '维生素A']),
      scene_tags: JSON.stringify(['日常', '快手', '生病']),
      texture_level: 'chunks',
      adult_version: JSON.stringify({
        ingredients: [{ name: '鸡蛋', amount: '2个', note: '' }],
        steps: [{ step: 1, action: '鸡蛋打散加盐温水蒸10分钟，淋生抽', time: 10, tools: ['蒸锅'], note: '' }],
        seasonings: [{ name: '盐', amount: '少量' }, { name: '生抽', amount: '少量' }],
      }),
      baby_version: JSON.stringify({
        age_range: '18-24个月',
        ingredients: [
          { name: '鸡蛋', amount: '1个', note: '' },
          { name: '温水', amount: '60ml', note: '' },
          { name: '菠菜碎', amount: '10g', note: '焯水' },
          { name: '胡萝卜碎', amount: '10g', note: '煮软' },
        ],
        steps: [
          { step: 1, action: '鸡蛋加温水打散过筛', time: 3, tools: [], note: '' },
          { step: 2, action: '蛋液中加入菜碎，蒸10分钟', time: 10, tools: ['蒸锅'], note: '' },
        ],
        nutrition_tips: '蒸蛋嫩滑易消化，加入蔬菜增加营养多样性',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify(['生病或食欲差时蒸蛋是好选择', '可加少量芝麻油增香']),
      tags: JSON.stringify(['辅食', '蒸蛋', '18个月', '生病']),
      is_active: true,
    },
    {
      id: 'baby_031',
      name: '宝宝版虾皮豆腐汤',
      name_en: 'Baby Shrimp Tofu Soup',
      type: 'baby',
      category: JSON.stringify(['辅食', '汤']),
      prep_time: 5,
      cook_time: 10,
      total_time: 15,
      difficulty: '简单',
      servings: '2份',
      stage: '18-24m',
      first_intro: false,
      key_nutrients: JSON.stringify(['钙', '蛋白质', '碘', '磷']),
      scene_tags: JSON.stringify(['日常', '补钙']),
      texture_level: 'chunks',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '豆腐', amount: '150g', note: '' },
          { name: '虾皮', amount: '5g', note: '' },
        ],
        steps: [{ step: 1, action: '豆腐切块与虾皮同煮5分钟，加盐', time: 8, tools: ['锅'], note: '' }],
        seasonings: [{ name: '盐', amount: '少量' }, { name: '葱', amount: '少量' }],
      }),
      baby_version: JSON.stringify({
        age_range: '18-24个月',
        ingredients: [
          { name: '嫩豆腐', amount: '60g', note: '' },
          { name: '虾皮', amount: '2g', note: '少量提鲜' },
          { name: '紫菜', amount: '少量', note: '' },
        ],
        steps: [
          { step: 1, action: '虾皮泡水10分钟去盐分', time: 10, tools: [], note: '' },
          { step: 2, action: '豆腐切小块，加水和虾皮紫菜煮5分钟', time: 8, tools: ['锅'], note: '不额外加盐' },
        ],
        nutrition_tips: '虾皮钙含量极高，豆腐也是优质钙源，双重补钙',
        allergy_alert: '虾皮含海鲜过敏原',
      }),
      cooking_tips: JSON.stringify(['虾皮泡水去盐很重要', '18个月后可接受少量碘盐来源']),
      tags: JSON.stringify(['辅食', '豆腐', '虾皮', '18个月', '补钙']),
      is_active: true,
    },
    {
      id: 'baby_032',
      name: '宝宝版花椰菜炒鸡蛋',
      name_en: 'Baby Cauliflower Egg Stir-fry',
      type: 'baby',
      category: JSON.stringify(['辅食', '炒菜']),
      prep_time: 5,
      cook_time: 10,
      total_time: 15,
      difficulty: '简单',
      servings: '1份',
      stage: '18-24m',
      first_intro: false,
      key_nutrients: JSON.stringify(['维生素C', '叶酸', '蛋白质', '维生素K']),
      scene_tags: JSON.stringify(['日常', '快手']),
      texture_level: 'chunks',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '花椰菜', amount: '150g', note: '' },
          { name: '鸡蛋', amount: '2个', note: '' },
        ],
        steps: [{ step: 1, action: '花椰菜焯水，鸡蛋炒散，混合翻炒加盐', time: 10, tools: ['锅'], note: '' }],
        seasonings: [{ name: '盐', amount: '少量' }, { name: '蒜', amount: '2瓣' }],
      }),
      baby_version: JSON.stringify({
        age_range: '18-24个月',
        ingredients: [
          { name: '花椰菜', amount: '60g', note: '只取花球，切小' },
          { name: '鸡蛋', amount: '1个', note: '' },
        ],
        steps: [
          { step: 1, action: '花椰菜焯水3分钟，切成小朵', time: 5, tools: ['锅'], note: '' },
          { step: 2, action: '鸡蛋炒熟，加入花椰菜翻炒均匀', time: 5, tools: ['锅'], note: '少油不加盐' },
        ],
        nutrition_tips: '花椰菜维生素C丰富，搭配鸡蛋营养互补',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify(['花椰菜切小一点更容易咀嚼', '鸡蛋炒散后加入花椰菜翻炒几下即可']),
      tags: JSON.stringify(['辅食', '花椰菜', '鸡蛋', '18个月']),
      is_active: true,
    },
    {
      id: 'baby_033',
      name: '宝宝肉末茄子',
      name_en: 'Baby Minced Pork Eggplant',
      type: 'baby',
      category: JSON.stringify(['辅食', '炒菜']),
      prep_time: 5,
      cook_time: 15,
      total_time: 20,
      difficulty: '简单',
      servings: '2份',
      stage: '18-24m',
      first_intro: false,
      key_nutrients: JSON.stringify(['铁', '蛋白质', '花青素', '钾']),
      scene_tags: JSON.stringify(['日常']),
      texture_level: 'chunks',
      adult_version: JSON.stringify({
        ingredients: [
          { name: '茄子', amount: '200g', note: '' },
          { name: '猪肉末', amount: '80g', note: '' },
        ],
        steps: [{ step: 1, action: '茄子切丁，肉末炒散，加茄子翻炒调味', time: 15, tools: ['锅'], note: '' }],
        seasonings: [{ name: '盐', amount: '少量' }, { name: '生抽', amount: '1勺' }],
      }),
      baby_version: JSON.stringify({
        age_range: '18-24个月',
        ingredients: [
          { name: '茄子', amount: '80g', note: '去皮切小丁' },
          { name: '猪肉末', amount: '25g', note: '' },
        ],
        steps: [
          { step: 1, action: '猪肉末入锅翻炒至变色', time: 3, tools: ['锅'], note: '' },
          { step: 2, action: '茄子去皮切小丁加入，加少量水焖5分钟至软', time: 8, tools: [], note: '' },
        ],
        nutrition_tips: '茄子皮含花青素抗氧化，但给小宝宝可去皮更易消化',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify(['18月宝宝可以不去皮，24月以上同大人', '可加2-3滴生抽调味']),
      tags: JSON.stringify(['辅食', '茄子', '肉末', '18个月']),
      is_active: true,
    },

    // ===== 24-36m 幼儿期（接近成人食物）=====
    {
      id: 'baby_034',
      name: '宝宝版西红柿炖牛腩',
      name_en: 'Baby Tomato Beef Brisket Stew',
      type: 'baby',
      category: JSON.stringify(['辅食', '炖菜']),
      prep_time: 10,
      cook_time: 60,
      total_time: 70,
      difficulty: '中等',
      servings: '4份',
      stage: '24-36m',
      first_intro: false,
      key_nutrients: JSON.stringify(['铁', '蛋白质', '胶原蛋白', '维生素C']),
      scene_tags: JSON.stringify(['日常', '节日']),
      texture_level: null,
      adult_version: JSON.stringify({
        ingredients: [
          { name: '牛腩', amount: '300g', note: '' },
          { name: '番茄', amount: '3个', note: '' },
          { name: '土豆', amount: '200g', note: '' },
        ],
        steps: [
          { step: 1, action: '牛腩焯水，番茄炒出汁，加牛腩土豆炖1小时', time: 70, tools: ['锅'], note: '' },
        ],
        seasonings: [{ name: '盐', amount: '少量' }, { name: '酱油', amount: '1勺' }],
      }),
      baby_version: JSON.stringify({
        age_range: '24-36个月',
        ingredients: [
          { name: '牛腩', amount: '60g', note: '切小块' },
          { name: '番茄', amount: '1个', note: '' },
          { name: '土豆', amount: '60g', note: '' },
        ],
        steps: [
          { step: 1, action: '牛腩焯水去浮沫', time: 5, tools: ['锅'], note: '' },
          { step: 2, action: '番茄去皮切块炒出汁，加牛腩和土豆', time: 5, tools: [], note: '' },
          { step: 3, action: '加水小火炖60分钟至牛腩酥烂', time: 60, tools: [], note: '可用压力锅30分钟' },
        ],
        nutrition_tips: '牛腩富含胶原蛋白和铁，炖烂后2岁宝宝也能咀嚼',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify(['可用压力锅大幅缩短时间', '汤汁可以拌饭给宝宝吃']),
      tags: JSON.stringify(['辅食', '牛腩', '番茄', '24个月']),
      is_active: true,
    },
    {
      id: 'baby_035',
      name: '宝宝版菠菜猪肝炒饭',
      name_en: 'Baby Spinach Pork Liver Fried Rice',
      type: 'baby',
      category: JSON.stringify(['辅食', '米饭']),
      prep_time: 10,
      cook_time: 15,
      total_time: 25,
      difficulty: '中等',
      servings: '2份',
      stage: '24-36m',
      first_intro: false,
      key_nutrients: JSON.stringify(['铁', '叶酸', '维生素A', '维生素B12']),
      scene_tags: JSON.stringify(['日常', '补铁']),
      texture_level: null,
      adult_version: JSON.stringify({
        ingredients: [
          { name: '猪肝', amount: '100g', note: '' },
          { name: '菠菜', amount: '100g', note: '' },
          { name: '米饭', amount: '1碗', note: '' },
        ],
        steps: [
          { step: 1, action: '猪肝切片焯水，菠菜焯水，炒饭', time: 15, tools: ['锅'], note: '' },
        ],
        seasonings: [{ name: '盐', amount: '少量' }, { name: '酱油', amount: '少量' }],
      }),
      baby_version: JSON.stringify({
        age_range: '24-36个月',
        ingredients: [
          { name: '猪肝', amount: '25g', note: '' },
          { name: '菠菜', amount: '30g', note: '' },
          { name: '米饭', amount: '半碗', note: '' },
          { name: '鸡蛋', amount: '1个', note: '' },
        ],
        steps: [
          { step: 1, action: '猪肝浸泡15分钟，蒸熟切小碎', time: 20, tools: ['蒸锅'], note: '' },
          { step: 2, action: '菠菜焯水切碎，鸡蛋炒散', time: 5, tools: ['锅'], note: '' },
          { step: 3, action: '加米饭翻炒，拌入猪肝碎和菠菜碎', time: 5, tools: [], note: '' },
        ],
        nutrition_tips: '猪肝每周最多2次，铁含量极高，搭配维生素C菠菜吸收更好',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify(['猪肝浸泡去血水很关键', '不能过量，每周1-2次即可']),
      tags: JSON.stringify(['辅食', '猪肝', '菠菜', '24个月', '补铁']),
      is_active: true,
    },
    {
      id: 'baby_036',
      name: '宝宝版鸡肉蔬菜饺子',
      name_en: 'Baby Chicken Vegetable Dumplings',
      type: 'baby',
      category: JSON.stringify(['辅食', '主食']),
      prep_time: 30,
      cook_time: 10,
      total_time: 40,
      difficulty: '中等',
      servings: '4份',
      stage: '24-36m',
      first_intro: false,
      key_nutrients: JSON.stringify(['蛋白质', '维生素', '碳水化合物', '矿物质']),
      scene_tags: JSON.stringify(['日常', '节日']),
      texture_level: null,
      adult_version: JSON.stringify({
        ingredients: [
          { name: '鸡肉', amount: '200g', note: '' },
          { name: '白菜', amount: '200g', note: '' },
          { name: '饺子皮', amount: '适量', note: '' },
        ],
        steps: [
          { step: 1, action: '鸡肉剁馅，白菜切碎挤水，调馅包饺子，煮熟', time: 40, tools: ['锅'], note: '' },
        ],
        seasonings: [{ name: '盐', amount: '少量' }, { name: '酱油', amount: '1勺' }, { name: '葱姜', amount: '少量' }],
      }),
      baby_version: JSON.stringify({
        age_range: '24-36个月',
        ingredients: [
          { name: '鸡胸肉', amount: '80g', note: '剁成细末' },
          { name: '白菜', amount: '80g', note: '剁碎挤水' },
          { name: '胡萝卜', amount: '30g', note: '擦细丝' },
          { name: '饺子皮', amount: '15张', note: '' },
        ],
        steps: [
          { step: 1, action: '鸡肉末与蔬菜碎混合，不加盐调馅', time: 5, tools: [], note: '' },
          { step: 2, action: '包成小饺子，煮10分钟', time: 15, tools: ['锅'], note: '' },
        ],
        nutrition_tips: '自制饺子控制食材，营养全面无添加',
        allergy_alert: '含麸质',
      }),
      cooking_tips: JSON.stringify(['可批量制作冷冻备用，随时水煮', '包小一点宝宝一口一个']),
      tags: JSON.stringify(['辅食', '饺子', '鸡肉', '24个月']),
      is_active: true,
    },
    {
      id: 'baby_037',
      name: '宝宝版清炒时蔬',
      name_en: 'Baby Stir-fried Seasonal Vegetables',
      type: 'baby',
      category: JSON.stringify(['辅食', '炒菜']),
      prep_time: 5,
      cook_time: 8,
      total_time: 13,
      difficulty: '简单',
      servings: '2份',
      stage: '24-36m',
      first_intro: false,
      key_nutrients: JSON.stringify(['维生素C', '膳食纤维', '叶酸', '钾']),
      scene_tags: JSON.stringify(['日常', '快手']),
      texture_level: null,
      adult_version: JSON.stringify({
        ingredients: [
          { name: '时令蔬菜', amount: '200g', note: '' },
        ],
        steps: [{ step: 1, action: '蔬菜洗净切段，蒜末爆香，大火翻炒加盐', time: 8, tools: ['锅'], note: '' }],
        seasonings: [{ name: '盐', amount: '少量' }, { name: '蒜', amount: '2瓣' }],
      }),
      baby_version: JSON.stringify({
        age_range: '24-36个月',
        ingredients: [
          { name: '西兰花/菠菜/豆角等', amount: '100g', note: '选当季蔬菜' },
        ],
        steps: [
          { step: 1, action: '蔬菜切小段或小朵，焯水', time: 3, tools: ['锅'], note: '' },
          { step: 2, action: '少油快炒，可加极少量盐', time: 5, tools: [], note: '2岁后可加少量盐' },
        ],
        nutrition_tips: '培养蔬菜多样性，每天尽量吃3种以上颜色蔬菜',
        allergy_alert: '',
      }),
      cooking_tips: JSON.stringify(['2岁后可开始加极少量盐', '每周更换不同蔬菜培养多样性']),
      tags: JSON.stringify(['辅食', '蔬菜', '24个月', '快手']),
      is_active: true,
    },
    {
      id: 'baby_038',
      name: '宝宝版三鲜汤',
      name_en: 'Baby Three-Fresh Soup',
      type: 'baby',
      category: JSON.stringify(['辅食', '汤']),
      prep_time: 10,
      cook_time: 15,
      total_time: 25,
      difficulty: '简单',
      servings: '3份',
      stage: '24-36m',
      first_intro: false,
      key_nutrients: JSON.stringify(['蛋白质', '钙', 'DHA', '维生素']),
      scene_tags: JSON.stringify(['日常', '补钙']),
      texture_level: null,
      adult_version: JSON.stringify({
        ingredients: [
          { name: '虾', amount: '100g', note: '' },
          { name: '豆腐', amount: '100g', note: '' },
          { name: '蛋花', amount: '1个', note: '' },
        ],
        steps: [{ step: 1, action: '虾豆腐煮汤，打入蛋花，加盐', time: 15, tools: ['锅'], note: '' }],
        seasonings: [{ name: '盐', amount: '少量' }],
      }),
      baby_version: JSON.stringify({
        age_range: '24-36个月',
        ingredients: [
          { name: '鲜虾', amount: '3只', note: '去壳去虾线' },
          { name: '嫩豆腐', amount: '60g', note: '' },
          { name: '鸡蛋', amount: '1个', note: '' },
        ],
        steps: [
          { step: 1, action: '虾仁和豆腐加水煮沸5分钟', time: 8, tools: ['锅'], note: '' },
          { step: 2, action: '打入鸡蛋搅散，煮熟成蛋花汤', time: 3, tools: [], note: '' },
        ],
        nutrition_tips: '三种食材提供完整蛋白质，钙质丰富',
        allergy_alert: '含虾等海鲜过敏原',
      }),
      cooking_tips: JSON.stringify(['汤鲜不需要加太多调料', '虾仁提前去虾线']),
      tags: JSON.stringify(['辅食', '虾', '豆腐', '24个月', '汤']),
      is_active: true,
    },
    {
      id: 'baby_039',
      name: '宝宝版黑芝麻糊',
      name_en: 'Baby Black Sesame Paste',
      type: 'baby',
      category: JSON.stringify(['辅食', '早餐']),
      prep_time: 5,
      cook_time: 5,
      total_time: 10,
      difficulty: '简单',
      servings: '2份',
      stage: '24-36m',
      first_intro: false,
      key_nutrients: JSON.stringify(['钙', '铁', '不饱和脂肪酸', '维生素E']),
      scene_tags: JSON.stringify(['日常', '补钙']),
      texture_level: null,
      adult_version: JSON.stringify({
        ingredients: [{ name: '黑芝麻', amount: '30g', note: '' }],
        steps: [{ step: 1, action: '黑芝麻研磨加热水调成糊，加糖', time: 5, tools: [], note: '' }],
        seasonings: [{ name: '糖', amount: '适量' }],
      }),
      baby_version: JSON.stringify({
        age_range: '24-36个月',
        ingredients: [
          { name: '黑芝麻粉', amount: '10g', note: '研磨细腻' },
          { name: '温热水', amount: '100ml', note: '' },
          { name: '婴儿米粉', amount: '1勺', note: '增加稠度' },
        ],
        steps: [
          { step: 1, action: '黑芝麻粉加温水和米粉搅拌均匀', time: 3, tools: [], note: '不加糖' },
          { step: 2, action: '小火加热2分钟至糊状', time: 2, tools: ['锅'], note: '' },
        ],
        nutrition_tips: '黑芝麻钙含量丰富，每100g含钙780mg，高于牛奶',
        allergy_alert: '芝麻为过敏原',
      }),
      cooking_tips: JSON.stringify(['黑芝麻研磨越细越好吸收', '不给宝宝吃整颗芝麻（噎呛风险）']),
      tags: JSON.stringify(['辅食', '黑芝麻', '24个月', '补钙', '早餐']),
      is_active: true,
    },
    {
      id: 'baby_040',
      name: '宝宝版蔬菜疙瘩汤',
      name_en: 'Baby Vegetable Gnocchi Soup',
      type: 'baby',
      category: JSON.stringify(['辅食', '汤']),
      prep_time: 10,
      cook_time: 15,
      total_time: 25,
      difficulty: '简单',
      servings: '2份',
      stage: '24-36m',
      first_intro: false,
      key_nutrients: JSON.stringify(['碳水化合物', '维生素', '蛋白质', '铁']),
      scene_tags: JSON.stringify(['日常', '生病', '快手']),
      texture_level: null,
      adult_version: JSON.stringify({
        ingredients: [
          { name: '面粉', amount: '100g', note: '' },
          { name: '番茄', amount: '1个', note: '' },
          { name: '鸡蛋', amount: '1个', note: '' },
        ],
        steps: [
          { step: 1, action: '番茄炒汁加水，面粉调稀淋入成疙瘩，打蛋花', time: 15, tools: ['锅'], note: '' },
        ],
        seasonings: [{ name: '盐', amount: '少量' }],
      }),
      baby_version: JSON.stringify({
        age_range: '24-36个月',
        ingredients: [
          { name: '面粉', amount: '30g', note: '' },
          { name: '番茄', amount: '半个', note: '' },
          { name: '鸡蛋', amount: '1个', note: '' },
          { name: '菠菜', amount: '20g', note: '焯水切碎' },
        ],
        steps: [
          { step: 1, action: '面粉加水调成细流状面糊', time: 3, tools: [], note: '' },
          { step: 2, action: '番茄去皮炒出汁，加水煮沸', time: 5, tools: ['锅'], note: '' },
          { step: 3, action: '面糊细流淋入，搅拌成疙瘩，打蛋花，加菠菜', time: 5, tools: [], note: '' },
        ],
        nutrition_tips: '疙瘩汤易消化，生病食欲差时的好选择',
        allergy_alert: '含麸质',
      }),
      cooking_tips: JSON.stringify(['面糊细流均匀淋入，边淋边搅拌', '适合生病不想吃东西的宝宝']),
      tags: JSON.stringify(['辅食', '疙瘩汤', '24个月', '生病']),
      is_active: true,
    },
  ]);
}
